Shader "CLG/PlayerShipHighlight"
{
  Properties
  {
    [HideInInspector] _MainTex ("Texture", 2D) = "white" {}
    [HideInInspector] _SDFLast ("Texture", 2D) = "gray" {}
    [HideInInspector] _SDFNew ("Texture", 2D) = "gray" {}
    [HideInInspector] _SDFLastMask ("Texture", 2D) = "gray" {}
    [HideInInspector] _SDFNewMask ("Texture", 2D) = "gray" {}
    _Smooth ("Smoothness", float) = 0.05
    _Intensity ("Intensity", float) = 2
    _Tint ("Tint", Color) = (1,1,1,1)
  }
  SubShader
  {
    Tags
    { 
      "PreviewType" = "Plane"
      "QUEUE" = "Transparent"
      "RenderType" = "Transparent"
    }
    LOD 100
    Pass // ind: 1, name: 
    {
      Tags
      { 
        "PreviewType" = "Plane"
        "QUEUE" = "Transparent"
        "RenderType" = "Transparent"
      }
      LOD 100
      ZWrite Off
      Blend SrcAlpha One
      GpuProgramID 49144
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyzw        0     NONE   float   xyz 
          // TEXCOORD                 0   xy          1     NONE   float   xy  
          // COLOR                    0   xyzw        2     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // TEXCOORD                 0   xy          0     NONE   float   xy  
          // SV_POSITION              0   xyzw        1      POS   float   xyzw
          // COLOR                    0   xyzw        2     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[4], immediateIndexed
          dcl_constantbuffer CB1[21], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xy
          dcl_input v2.xyzw
          dcl_output o0.xy
          dcl_output_siv o1.xyzw, position
          dcl_output o2.xyzw
          dcl_temps 2
          mov o0.xy, v1.xyxx
          mul r0.xyzw, v0.yyyy, cb0[1].xyzw
          mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
          mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
          add r0.xyzw, r0.xyzw, cb0[3].xyzw
          mul r1.xyzw, r0.yyyy, cb1[18].xyzw
          mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
          mad o1.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
          mov o2.xyzw, v2.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
        SubProgram "vulkan"
        {
          
          "!!vulkan
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // TEXCOORD                 0   xy          0     NONE   float   xy  
          // SV_POSITION              0   xyzw        1      POS   float       
          // COLOR                    0   xyzw        2     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_Target                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_constantbuffer CB0[4], immediateIndexed
          dcl_sampler s0, mode_default
          dcl_sampler s1, mode_default
          dcl_sampler s2, mode_default
          dcl_sampler s3, mode_default
          dcl_sampler s4, mode_default
          dcl_resource_texture2d (float,float,float,float) t0
          dcl_resource_texture2d (float,float,float,float) t1
          dcl_resource_texture2d (float,float,float,float) t2
          dcl_resource_texture2d (float,float,float,float) t3
          dcl_resource_texture2d (float,float,float,float) t4
          dcl_input_ps linear v0.xy
          dcl_input_ps linear v2.xyzw
          dcl_output o0.xyzw
          dcl_temps 3
          sample r0.xyzw, v0.xyxx, t3.xyzw, s3
          sample r1.xyzw, v0.xyxx, t4.xyzw, s4
          add r0.y, -r0.x, r1.x
          mad r0.x, v2.w, r0.y, r0.x
          add r0.x, r0.x, l(-0.500000)
          add r0.y, r1.x, l(-0.500000)
          add r0.xy, r0.xyxx, cb0[2].yyyy
          add r0.z, cb0[2].y, cb0[2].y
          div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
          mul_sat r0.x, r0.z, r0.x
          mad r0.w, r0.x, l(-2.000000), l(3.000000)
          mul r0.x, r0.x, r0.x
          mul r0.x, r0.x, r0.w
          sample r1.xyzw, v0.xyxx, t2.xyzw, s2
          sample r2.xyzw, v0.xyxx, t1.xyzw, s1
          add r0.w, r1.x, -r2.x
          mad r0.w, v2.w, r0.w, r2.x
          add r0.w, r0.w, l(-0.500000)
          add r0.w, r0.w, cb0[2].y
          mul_sat r0.yw, r0.zzzz, r0.yyyw
          mad r0.z, r0.w, l(-2.000000), l(3.000000)
          mul r0.w, r0.w, r0.w
          mad r1.w, r0.z, r0.w, -r0.x
          mad r0.x, r0.y, l(-2.000000), l(3.000000)
          mul r0.y, r0.y, r0.y
          mad r0.zw, v0.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -0.500000, -0.500000)
          sample r2.xyzw, r0.zwzz, t0.xyzw, s0
          mad_sat r0.xyzw, -r0.xxxx, r0.yyyy, r2.xyzw
          mov r1.xyz, v2.xyzx
          add r0.xyzw, -r1.xyzw, r0.xyzw
          add r2.x, v2.w, l(-0.950000)
          mul_sat r2.x, r2.x, l(19.999996)
          mad r2.y, r2.x, l(-2.000000), l(3.000000)
          mul r2.x, r2.x, r2.x
          mul r2.x, r2.x, r2.y
          mad r0.xyzw, r2.xxxx, r0.xyzw, r1.xyzw
          mul r1.xyz, cb0[2].xxxx, cb0[3].xyzx
          mul o0.xyz, r0.xyzx, r1.xyzx
          mov o0.w, r0.w
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  FallBack Off
}
