Shader "Sprite Shaders URP/Lit Sprite/Color/Strong Tint (Override) Lit PlayerLightSourceColored"
{
  Properties
  {
    [NoScaleOffset] _MainTex ("Main Texture", 2D) = "white" {}
    [NoScaleOffset] _NormalMap ("Normal Map", 2D) = "white" {}
    _Normal_Strength ("Normal Strength", Range(-4, 4)) = 1
    _Intensity ("Intensity", float) = 0
    [HDR] _Tint_Color ("Tint Color", Color) = (1,1,1,1)
    Vector1_2f3c043e4c4b435f8bd6537a77df6a10 ("Player Light Heigth", float) = 3
    Vector1_fe7619cdfcb24592b281626c676fcfd3_2 ("Hard", Range(0, 1)) = 0.2
    Vector1_32944f22e62c428180641c5823208508 ("Hard Threshold", Range(0, 1)) = 0.5
    Vector1_3cc7bee8546345fbaa61727532d58e45 ("Hard Smoothness", Range(0, 0.1)) = 0.01
    Vector1_039de4a82ec14d468292b6a8689b1cd5 ("Specular Power", Range(1, 10)) = 1
    _ColorOrAlbedo ("ColorOrAlbedo", Range(0, 1)) = 1
    Color_199605a3731644e89aaa94c6282ce13b ("Mid Color", Color) = (0.5372549,0.3333333,0.1411765,1)
    Vector1_3e05109515914ace9d9a46f49d57ed11 ("Reserve Normal Strength", Range(0, 1)) = 0.42
    _OutlineThickness ("Outline Thickness", float) = 0
    _OutlineColor ("Outline Color", Color) = (0,0,0,0)
    _Roll ("Roll", float) = 0
    [NoScaleOffset] _MaskTex ("HeightMap", 2D) = "white" {}
    _HMStrength ("HeightMapStrength", float) = 0
    _CenterData ("CenterData", Vector) = (0,0,1,0)
    _HMData ("HeightMapData", Vector) = (0.2,1,1,0.5)
    unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" {}
    unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" {}
    unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" {}
    [Toggle] CORNERS ("Sample Corners", float) = 0
  }
  SubShader
  {
    Tags
    { 
      "QUEUE" = "Transparent"
      "RenderPipeline" = "UniversalPipeline"
      "RenderType" = "Transparent"
      "UniversalMaterialType" = "Unlit"
    }
    Pass // ind: 1, name: Pass
    {
      Name "Pass"
      Tags
      { 
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      GpuProgramID 46010
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyz         1     NONE   float   xyz 
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[72].xyzw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
        SubProgram "vulkan"
        {
          
          "!!vulkan
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyz         1     NONE   float   xy  
          // TEXCOORD                 1   xyzw        2     NONE   float   xy  
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[131], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_constantbuffer CB2[14], immediateIndexed
          dcl_sampler s0, mode_default
          dcl_sampler s1, mode_default
          dcl_sampler s2, mode_default
          dcl_resource_texture2d (float,float,float,float) t0
          dcl_resource_texture2d (float,float,float,float) t1
          dcl_resource_texture2d (float,float,float,float) t2
          dcl_input_ps linear v1.xy
          dcl_input_ps linear v2.xy
          dcl_input_ps linear v3.xyzw
          dcl_output o0.xyzw
          dcl_temps 9
          log r0.xyz, |cb0[126].xyzx|
          mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
          exp r0.xyz, r0.xyzx
          mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
          mul r1.xyz, cb0[126].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb0[126].xyzx
          movc r0.xyz, r2.xyzx, r1.xyzx, r0.xyzx
          log r1.xyz, |cb0[127].xyzx|
          mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
          exp r1.xyz, r1.xyzx
          mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
          mul r2.xyz, cb0[127].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r3.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb0[127].xyzx
          movc r1.xyz, r3.xyzx, r2.xyzx, r1.xyzx
          mad r0.xyz, r1.xyzx, cb0[128].wwww, r0.xyzx
          log r1.xyz, |cb0[125].xyzx|
          mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
          exp r1.xyz, r1.xyzx
          mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
          mul r2.xyz, cb0[125].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r3.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb0[125].xyzx
          movc r1.xyz, r3.xyzx, r2.xyzx, r1.xyzx
          mad r1.xyz, r1.xyzx, cb0[128].wwww, cb0[124].xyzx
          mul r2.xyz, cb0[123].xyzx, cb0[123].wwww
          mad r1.xyz, r1.xyzx, cb0[124].wwww, -r2.xyzx
          mov r3.y, v2.y
          sample_indexable(texture2d)(float,float,float,float) r0.w, v2.xyxx, t2.xzwy, s2
          add r0.w, -r0.w, l(1.000000)
          mul r1.w, r0.w, cb2[9].x
          mul r0.w, r0.w, cb0[129].w
          mul r4.xyz, r1.wwww, l(0.017453, -0.017453, 0.017453, 0.000000)
          sincos r4.x, r5.x, r4.x
          div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
          mad r2.w, v2.x, l(2.000000), l(-1.000000)
          mul r3.x, r1.w, r2.w
          mad r3.xy, r3.xyxx, l(0.500000, 1.000000, 0.000000, 0.000000), l(0.500000, 0.000000, 0.000000, 0.000000)
          sample_indexable(texture2d)(float,float,float,float) r1.w, r3.xyxx, t2.yzwx, s2
          mul r3.x, r1.w, cb2[11].x
          add r1.w, r1.w, -cb2[13].w
          mad r2.w, r4.x, r3.x, r2.w
          div r3.xz, r2.wwww, r5.xxxx
          mov r3.y, v2.y
          mad r3.xyz, r3.xyzx, l(0.500000, 1.000000, 0.500000, 0.000000), l(0.500000, 0.000000, 0.010000, 0.000000)
          sample_indexable(texture2d)(float,float,float,float) r5.xyz, r3.xyxx, t1.xywz, s1
          mul r5.x, r5.x, r5.z
          mad r4.xw, r5.xxxy, l(2.000000, 0.000000, 0.000000, 2.000000), l(-1.000000, 0.000000, 0.000000, -1.000000)
          dp2 r2.w, r4.xwxx, r4.xwxx
          min r2.w, r2.w, l(1.000000)
          add r2.w, -r2.w, l(1.000000)
          sqrt r2.w, r2.w
          max r2.w, r2.w, l(0.000000)
          add r2.w, r2.w, l(-1.000000)
          mul r3.w, cb2[2].x, l(1.500000)
          mov_sat r5.x, r3.w
          mul r6.xy, r3.wwww, r4.xwxx
          mul r3.w, r4.w, r4.x
          ge r3.w, l(0.990000), r3.w
          and r3.w, r3.w, l(0x3f800000)
          mad r6.z, r5.x, r2.w, l(1.000000)
          dp3 r2.w, r6.xyzx, r6.xyzx
          rsq r2.w, r2.w
          mul r5.xyz, r2.wwww, r6.xyzx
          sincos r4.x, r6.x, r4.y
          sincos r7.x, r8.x, r4.z
          div r2.w, r7.x, r8.x
          mov r7.z, r4.x
          mov r7.y, r6.x
          mov r7.x, -r4.x
          dp2 r4.z, r7.xyxx, r5.xzxx
          dp2 r4.x, r7.yzyy, r5.xzxx
          mov r4.y, r5.y
          mov r4.w, l(1.000000)
          dp4 r5.x, r4.xyzw, cb1[4].xyzw
          dp4 r5.y, r4.xyzw, cb1[5].xyzw
          dp4 r5.z, r4.xyzw, cb1[6].xyzw
          add r4.xyz, cb0[128].xyzx, -cb1[3].xyzx
          add r4.z, r4.z, cb2[4].x
          dp3 r5.w, r4.xyzx, r4.xyzx
          rsq r5.w, r5.w
          mul r6.xyz, r4.xyzx, r5.wwww
          dp3_sat r4.z, r5.xyzx, r6.xyzx
          add r5.x, -cb2[4].w, cb2[4].z
          add r5.y, r4.z, -r5.x
          add r5.z, cb2[4].w, cb2[4].z
          add r5.x, -r5.x, r5.z
          div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
          mul_sat r5.x, r5.x, r5.y
          mad r5.y, r5.x, l(-2.000000), l(3.000000)
          mul r5.x, r5.x, r5.x
          dp2 r5.x, r5.yyyy, r5.xxxx
          add r5.x, r5.x, l(-1.000000)
          mad r5.x, r5.x, cb2[4].y, r4.z
          add r5.x, r5.x, cb0[122].w
          mad r1.xyz, r5.xxxx, r1.xyzx, r2.xyzx
          mov_sat r5.x, r5.x
          sample_indexable(texture2d)(float,float,float,float) r6.xyzw, r3.xyxx, t0.xyzw, s0
          mul_sat r2.x, r3.z, l(50.000050)
          mad r3.xyz, r6.xyzx, v3.xyzx, -cb2[6].xyzx
          mul r6.xyzw, r6.xyzw, v3.xyzw
          mad r3.xyz, cb2[5].yyyy, r3.xyzx, cb2[6].xyzx
          mad r0.xyz, -r3.xyzx, r1.xyzx, r0.xyzx
          mul r1.xyz, r1.xyzx, r3.xyzx
          log r2.y, r4.z
          add r2.z, r4.z, -r5.x
          mul r2.y, r2.y, cb2[5].x
          exp r2.y, r2.y
          mul r2.y, r2.y, cb0[126].w
          mad r0.xyz, r2.yyyy, r0.xyzx, r1.xyzx
          mov r4.w, l(0.001000)
          dp3 r1.x, r4.xywx, r4.xywx
          rsq r1.x, r1.x
          mul r1.xyz, r1.xxxx, r4.xywx
          mad r2.y, r2.x, l(-2.000000), l(3.000000)
          mul r2.x, r2.x, r2.x
          dp2 r2.x, r2.yyyy, r2.xxxx
          add r2.x, r2.x, l(-1.000000)
          mul r2.x, r2.x, cb2[7].x
          add r2.y, -cb2[7].x, l(1.000000)
          dp2 r3.x, r2.xyxx, r2.xyxx
          rsq r3.x, r3.x
          mul r3.xy, r2.xyxx, r3.xxxx
          mov r3.z, l(1.000000)
          dp3 r4.x, r3.xyzx, cb1[4].xzwx
          dp3 r4.y, r3.xyzx, cb1[5].xzwx
          dp3 r4.z, r3.xyzx, cb1[6].xzwx
          dp3 r1.x, r4.xyzx, r1.xyzx
          add r1.x, r1.x, l(1.000000)
          mad r3.xyz, -r1.xxxx, r6.xyzx, r0.xyzx
          mul r1.xyz, r6.xyzx, r1.xxxx
          mov o0.w, r6.w
          mad r1.xyz, r3.wwww, r3.xyzx, r1.xyzx
          log r3.xyz, |cb2[3].xyzx|
          mul r3.xyz, r3.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
          exp r3.xyz, r3.xyzx
          mad r3.xyz, r3.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
          mul r4.xyz, cb2[3].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r5.yzw, l(0.000000, 0.003131, 0.003131, 0.003131), cb2[3].xxyz
          movc r3.xyz, r5.yzwy, r4.xyzx, r3.xyzx
          add r3.xyz, -r1.xyzx, r3.xyzx
          mad r1.xyz, cb2[2].yyyy, r3.xyzx, r1.xyzx
          add r3.xyz, r1.xyzx, -cb0[129].xyzx
          add r2.xy, v1.xyxx, -cb2[12].xyxx
          dp2 r2.x, r2.xyxx, cb2[12].zwzz
          mul r2.x, r2.w, r2.x
          mul r2.x, r2.x, cb2[13].z
          mad r1.w, r1.w, cb2[13].y, r2.x
          mul r2.x, r0.w, r1.w
          mad r0.w, r1.w, r0.w, l(1.000000)
          ge r1.w, r1.w, l(0.000000)
          and r1.w, r1.w, l(0x3f800000)
          mul r2.x, r2.x, l(1.442695)
          exp r2.x, r2.x
          mad r2.xyw, r2.xxxx, r3.xyxz, cb0[129].xyxz
          mad r1.xyz, r1.xyzx, r0.wwww, -r2.xywx
          mad r1.xyz, r1.wwww, r1.xyzx, r2.xywx
          ge r2.xyw, cb0[130].xxxx, l(2.500000, 1.500000, 0.000000, 0.500000)
          and r2.xyw, r2.xyxw, l(0x3f800000, 0x3f800000, 0, 0x3f800000)
          mad r0.w, r2.x, r2.z, r5.x
          add r3.xyz, -r0.xyzx, r0.wwww
          mad r0.xyz, r2.yyyy, r3.xyzx, r0.xyzx
          dp3 r0.x, r0.xyzx, l(0.212673, 0.715152, 0.072175, 0.000000)
          add r0.xyz, -r1.xyzx, r0.xxxx
          mad o0.xyz, r2.wwww, r0.xyzx, r1.xyzx
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 2, name: DepthOnly
    {
      Name "DepthOnly"
      Tags
      { 
        "LIGHTMODE" = "DepthOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      ColorMask 0
      GpuProgramID 153563
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyzw        1     NONE   float   xyzw
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyzw
          dcl_output o2.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r0.xyzw, cb0[72].xyzw
          mov o1.xyzw, v3.xyzw
          mov o2.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
        SubProgram "vulkan"
        {
          
          "!!vulkan
          020303030000000000000000000000000000000000000000000000000000000000000000000044584243A25D470CCF675E3C3741F8037319252C01000000C4160000030000002C000000B4000000E80000004953474E80000000040000000800000068000000000000000100000003000000000000000F00000074000000000000000000000003000000010000000703000074000000010000000000000003000000020000000F03000074000000020000000000000003000000030000000F0F000053565F504F534954494F4E00544558434F4F524400ABABAB4F53474E2C000000010000000800000020000000000000000000000003000000000000000F00000053565F54415247455400ABAB53484558D415000050000000750500006A08000159000004468E2000000000008300000059000004468E2000010000000700000059000004468E2000020000000E0000005A00000300601000000000005A00000300601000010000005A000003006010000200000058180004007010000000000055550000581800040070100001000000555500005818000400701000020000005555000062100003321010000100000062100003321010000200000062100003F21010000300000065000003F22010000000000068000002090000002F00000772001000000000004682208081000000000000007E0000003800000A72001000000000004602100000000000024000005555D53E5555D53E5555D53E0000000019000005720010000000000046021000000000003200000F72001000000000004602100000000000024000003D0A873F3D0A873F3D0A873F0000000002400000AE4761BDAE4761BDAE4761BD000000003800000B720010000100000046822000000000007E0000000240000052B84E4152B84E4152B84E41000000001D00000B7200100002000000024000001C2E4D3B1C2E4D3B1C2E4D3B0000000046822000000000007E0000003700000972001000000000004602100002000000460210000100000046021000000000002F00000772001000010000004682208081000000000000007F0000003800000A72001000010000004602100001000000024000005555D53E5555D53E5555D53E0000000019000005720010000100000046021000010000003200000F72001000010000004602100001000000024000003D0A873F3D0A873F3D0A873F0000000002400000AE4761BDAE4761BDAE4761BD000000003800000B720010000200000046822000000000007F0000000240000052B84E4152B84E4152B84E41000000001D00000B7200100003000000024000001C2E4D3B1C2E4D3B1C2E4D3B0000000046822000000000007F0000003700000972001000010000004602100003000000460210000200000046021000010000003200000A72001000000000004602100001000000F68F2000000000008000000046021000000000002F00000772001000010000004682208081000000000000007D0000003800000A72001000010000004602100001000000024000005555D53E5555D53E5555D53E0000000019000005720010000100000046021000010000003200000F72001000010000004602100001000000024000003D0A873F3D0A873F3D0A873F0000000002400000AE4761BDAE4761BDAE4761BD000000003800000B720010000200000046822000000000007D0000000240000052B84E4152B84E4152B84E41000000001D00000B7200100003000000024000001C2E4D3B1C2E4D3B1C2E4D3B0000000046822000000000007D0000003700000972001000010000004602100003000000460210000200000046021000010000003200000B72001000010000004602100001000000F68F2000000000008000000046822000000000007C00000038000009720010000200000046822000000000007B000000F68F2000000000007B0000003200000B72001000010000004602100001000000F68F2000000000007C0000004602108041000000020000003600000522001000030000001A101000020000004500008BC20000804355150082001000000000004610100002000000867710000200000000601000020000000000000882001000000000003A0010804100000000000000014000000000803F3800000882001000010000003A001000000000000A80200002000000090000003800000882001000000000003A001000000000003A80200000000000810000003800000A7200100004000000F60F1000010000000240000039FA8E3C35FA8EBC35FA8E3C000000004D000007120010000400000012001000050000000A001000040000000E00000A8200100001000000024000000000803F0000803F0000803F0000803F0A001000050000003200000982001000020000000A10100002000000014000000000004001400000000080BF3800000712001000030000003A001000010000003A001000020000003200000F32001000030000004600100003000000024000000000003F0000803F0000000000000000024000000000003F0000000000000000000000004500008BC20000804355150082001000010000004600100003000000967310000200000000601000020000003800000812001000030000003A001000010000000A802000020000000B0000000000000982001000010000003A001000010000003A80208041000000020000000D0000003200000982001000020000000A001000040000000A001000030000003A001000020000000E0000075200100003000000F60F10000200000006001000050000003600000522001000030000001A101000020000003200000F72001000030000004602100003000000024000000000003F0000803F0000003F00000000024000000000003F0000000000D7233C000000004500008BC20000804355150072001000050000004600100003000000467B10000100000000601000010000003800000712001000050000000A001000050000002A001000050000003200000F92001000040000000604100005000000024000000000004000000000000000000000004002400000000080BF0000000000000000000080BF0F0000078200100002000000C600100004000000C6001000040000003300000782001000020000003A00100002000000014000000000803F0000000882001000020000003A0010804100000002000000014000000000803F4B00000582001000020000003A001000020000003400000782001000020000003A00100002000000014000009595E6240000000782001000020000003A0010000200000001400000000080BF3800000882001000030000000A8020000200000002000000014000000000C03F3620000512001000050000003A00100003000000380000073200100006000000F60F100003000000C6001000040000003800000782001000030000003A001000040000000A001000040000001D000007820010000300000001400000A4707D3F3A001000030000000100000782001000030000003A00100003000000014000000000803F3200000942001000060000000A001000050000003A00100002000000014000000000803F100000078200100002000000460210000600000046021000060000004400000582001000020000003A00100002000000380000077200100005000000F60F10000200000046021000060000004D000007120010000400000012001000060000001A001000040000004D000007120010000700000012001000080000002A001000040000000E00000782001000020000000A001000070000000A001000080000003600000542001000070000000A001000040000003600000522001000070000000A001000060000003600000612001000070000000A00108041000000040000000F0000074200100004000000460010000700000086001000050000000F0000071200100004000000960510000700000086001000050000003600000522001000040000001A00100005000000360000058200100004000000014000000000803F110000081200100005000000460E100004000000468E20000100000004000000110000082200100005000000460E100004000000468E20000100000005000000110000084200100005000000460E100004000000468E200001000000060000000000000A7200100004000000468220000000000080000000468220804100000001000000030000000000000842001000040000002A001000040000000A8020000200000004000000100000078200100005000000460210000400000046021000040000004400000582001000050000003A001000050000003800000772001000060000004602100004000000F60F100005000000102000074200100004000000460210000500000046021000060000000000000A12001000050000003A8020804100000002000000040000002A80200002000000040000000000000822001000050000002A001000040000000A00108041000000050000000000000942001000050000003A80200002000000040000002A80200002000000040000000000000812001000050000000A00108041000000050000002A001000050000000E00000A1200100005000000024000000000803F0000803F0000803F0000803F0A001000050000003820000712001000050000000A001000050000001A001000050000003200000922001000050000000A0010000500000001400000000000C001400000000040403800000712001000050000000A001000050000000A001000050000000F0000071200100005000000560510000500000006001000050000000000000712001000050000000A0010000500000001400000000080BF3200000A12001000050000000A001000050000001A80200002000000040000002A001000040000000000000812001000050000000A001000050000003A802000000000007A0000003200000972001000010000000600100005000000460210000100000046021000020000003620000512001000050000000A001000050000004500008BC200008043551500F2001000060000004600100003000000467E10000000000000601000000000003820000712001000020000002A00100003000000014000000D0048423200000B7200100003000000460210000600000046121000030000004682208041000000020000000600000038000007F200100006000000460E100006000000461E1000030000003200000B720010000300000056852000020000000500000046021000030000004682200002000000060000003200000A720010000000000046021080410000000300000046021000010000004602100000000000380000077200100001000000460210000100000046021000030000002F00000522001000020000002A001000040000000000000842001000020000002A001000040000000A00108041000000050000003800000822001000020000001A001000020000000A80200002000000050000001900000522001000020000001A001000020000003800000822001000020000001A001000020000003A802000000000007E000000320000097200100000000000560510000200000046021000000000004602100001000000360000058200100004000000014000006F12833A100000071200100001000000460310000400000046031000040000004400000512001000010000000A00100001000000380000077200100001000000060010000100000046031000040000003200000922001000020000000A0010000200000001400000000000C001400000000040403800000712001000020000000A001000020000000A001000020000000F0000071200100002000000560510000200000006001000020000000000000712001000020000000A0010000200000001400000000080BF3800000812001000020000000A001000020000000A80200002000000070000000000000922001000020000000A802080410000000200000007000000014000000000803F0F0000071200100003000000460010000200000046001000020000004400000512001000030000000A0010000300000038000007320010000300000046001000020000000600100003000000360000054200100003000000014000000000803F100000081200100004000000460210000300000086832000010000000400000010000008220010000400000046021000030000008683200001000000050000001000000842001000040000004602100003000000868320000100000006000000100000071200100001000000460210000400000046021000010000000000000712001000010000000A00100001000000014000000000803F3200000A720010000300000006001080410000000100000046021000060000004602100000000000380000077200100001000000460210000600000006001000010000003600000582201000000000003A00100006000000320000097200100001000000F60F100003000000460210000300000046021000010000002F0000077200100003000000468220808100000002000000030000003800000A72001000030000004602100003000000024000005555D53E5555D53E5555D53E0000000019000005720010000300000046021000030000003200000F72001000030000004602100003000000024000003D0A873F3D0A873F3D0A873F0000000002400000AE4761BDAE4761BDAE4761BD000000003800000B72001000040000004682200002000000030000000240000052B84E4152B84E4152B84E41000000001D00000BE20010000500000002400000000000001C2E4D3B1C2E4D3B1C2E4D3B06892000020000000300000037000009720010000300000096071000050000004602100004000000460210000300000000000008720010000300000046021080410000000100000046021000030000003200000A72001000010000005685200002000000020000004602100003000000460210000100000000000009720010000300000046021000010000004682208041000000000000008100000000000009320010000200000046101000010000004680208041000000020000000C0000000F00000812001000020000004600100002000000E68A2000020000000C0000003800000712001000020000003A001000020000000A001000020000003800000812001000020000000A001000020000002A802000020000000D0000003200000A82001000010000003A001000010000001A802000020000000D0000000A001000020000003800000712001000020000003A001000000000003A001000010000003200000982001000000000003A001000010000003A00100000000000014000000000803F1D00000782001000010000003A0010000100000001400000000000000100000782001000010000003A00100001000000014000000000803F3800000712001000020000000A00100002000000014000003BAAB83F1900000512001000020000000A001000020000003200000AB200100002000000060010000200000046081000030000004688200000000000810000003200000A72001000010000004602100001000000F60F100000000000460310804100000002000000320000097200100001000000F60F100001000000460210000100000046031000020000001D00000BB20010000200000006802000000000008200000002400000000020400000C03F000000000000003F0100000AB200100002000000460C100002000000024000000000803F0000803F000000000000803F3200000982001000000000000A001000020000002A001000020000000A00100005000000000000087200100003000000460210804100000000000000F60F1000000000003200000972001000000000005605100002000000460210000300000046021000000000001000000A1200100000000000460210000000000002400000EDC6593E3714373F7DD0933D000000000000000872001000000000004602108041000000010000000600100000000000320000097220100000000000F60F100002000000460210000000000046021000010000003E000001
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyzw        1     NONE   float       
          // TEXCOORD                 1   xyzw        2     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_output o0.xyzw
          mov o0.xyzw, l(0,0,0,0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  SubShader
  {
    Tags
    { 
      "QUEUE" = "Transparent"
      "RenderPipeline" = "UniversalPipeline"
      "RenderType" = "Transparent"
      "UniversalMaterialType" = "Unlit"
    }
    Pass // ind: 1, name: Pass
    {
      Name "Pass"
      Tags
      { 
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      GpuProgramID 251628
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyz         1     NONE   float   xyz 
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[72].xyzw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyz         1     NONE   float   xy  
          // TEXCOORD                 1   xyzw        2     NONE   float   xy  
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_constantbuffer CB0[131], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_constantbuffer CB2[14], immediateIndexed
          dcl_sampler s0, mode_default
          dcl_sampler s1, mode_default
          dcl_sampler s2, mode_default
          dcl_resource_texture2d (float,float,float,float) t0
          dcl_resource_texture2d (float,float,float,float) t1
          dcl_resource_texture2d (float,float,float,float) t2
          dcl_input_ps linear v1.xy
          dcl_input_ps linear v2.xy
          dcl_input_ps linear v3.xyzw
          dcl_output o0.xyzw
          dcl_temps 9
          log r0.xyz, |cb0[126].xyzx|
          mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
          exp r0.xyz, r0.xyzx
          mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
          mul r1.xyz, cb0[126].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb0[126].xyzx
          movc r0.xyz, r2.xyzx, r1.xyzx, r0.xyzx
          log r1.xyz, |cb0[127].xyzx|
          mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
          exp r1.xyz, r1.xyzx
          mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
          mul r2.xyz, cb0[127].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r3.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb0[127].xyzx
          movc r1.xyz, r3.xyzx, r2.xyzx, r1.xyzx
          mad r0.xyz, r1.xyzx, cb0[128].wwww, r0.xyzx
          log r1.xyz, |cb0[125].xyzx|
          mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
          exp r1.xyz, r1.xyzx
          mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
          mul r2.xyz, cb0[125].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r3.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb0[125].xyzx
          movc r1.xyz, r3.xyzx, r2.xyzx, r1.xyzx
          mad r1.xyz, r1.xyzx, cb0[128].wwww, cb0[124].xyzx
          mul r2.xyz, cb0[123].xyzx, cb0[123].wwww
          mad r1.xyz, r1.xyzx, cb0[124].wwww, -r2.xyzx
          mov r3.y, v2.y
          sample r4.xyzw, v2.xyxx, t2.xyzw, s2
          add r0.w, -r4.y, l(1.000000)
          mul r1.w, r0.w, cb2[9].x
          mul r0.w, r0.w, cb0[129].w
          mul r4.xyz, r1.wwww, l(0.017453, -0.017453, 0.017453, 0.000000)
          sincos r4.x, r5.x, r4.x
          div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
          mad r2.w, v2.x, l(2.000000), l(-1.000000)
          mul r3.x, r1.w, r2.w
          mad r3.xy, r3.xyxx, l(0.500000, 1.000000, 0.000000, 0.000000), l(0.500000, 0.000000, 0.000000, 0.000000)
          sample r3.xyzw, r3.xyxx, t2.xyzw, s2
          mul r1.w, r3.x, cb2[11].x
          add r3.x, r3.x, -cb2[13].w
          mad r1.w, r4.x, r1.w, r2.w
          div r5.xz, r1.wwww, r5.xxxx
          mov r5.y, v2.y
          mad r3.yzw, r5.xxyz, l(0.000000, 0.500000, 1.000000, 0.500000), l(0.000000, 0.500000, 0.000000, 0.010000)
          sample r5.xyzw, r3.yzyy, t1.xyzw, s1
          mul r5.x, r5.x, r5.w
          mad r4.xw, r5.xxxy, l(2.000000, 0.000000, 0.000000, 2.000000), l(-1.000000, 0.000000, 0.000000, -1.000000)
          dp2 r1.w, r4.xwxx, r4.xwxx
          min r1.w, r1.w, l(1.000000)
          add r1.w, -r1.w, l(1.000000)
          sqrt r1.w, r1.w
          max r1.w, r1.w, l(0.000000)
          add r1.w, r1.w, l(-1.000000)
          mul r2.w, cb2[2].x, l(1.500000)
          mov_sat r5.x, r2.w
          mul r6.xy, r2.wwww, r4.xwxx
          mul r2.w, r4.w, r4.x
          ge r2.w, l(0.990000), r2.w
          and r2.w, r2.w, l(0x3f800000)
          mad r6.z, r5.x, r1.w, l(1.000000)
          dp3 r1.w, r6.xyzx, r6.xyzx
          rsq r1.w, r1.w
          mul r5.xyz, r1.wwww, r6.xyzx
          sincos r4.x, r6.x, r4.y
          sincos r7.x, r8.x, r4.z
          div r1.w, r7.x, r8.x
          mov r7.z, r4.x
          mov r7.y, r6.x
          mov r7.x, -r4.x
          dp2 r4.z, r7.xyxx, r5.xzxx
          dp2 r4.x, r7.yzyy, r5.xzxx
          mov r4.y, r5.y
          mov r4.w, l(1.000000)
          dp4 r5.x, r4.xyzw, cb1[4].xyzw
          dp4 r5.y, r4.xyzw, cb1[5].xyzw
          dp4 r5.z, r4.xyzw, cb1[6].xyzw
          add r4.xyz, cb0[128].xyzx, -cb1[3].xyzx
          add r4.z, r4.z, cb2[4].x
          dp3 r5.w, r4.xyzx, r4.xyzx
          rsq r5.w, r5.w
          mul r6.xyz, r4.xyzx, r5.wwww
          dp3_sat r4.z, r5.xyzx, r6.xyzx
          add r5.x, -cb2[4].w, cb2[4].z
          add r5.y, r4.z, -r5.x
          add r5.z, cb2[4].w, cb2[4].z
          add r5.x, -r5.x, r5.z
          div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
          mul_sat r5.x, r5.x, r5.y
          mad r5.y, r5.x, l(-2.000000), l(3.000000)
          mul r5.x, r5.x, r5.x
          dp2 r5.x, r5.yyyy, r5.xxxx
          add r5.x, r5.x, l(-1.000000)
          mad r5.x, r5.x, cb2[4].y, r4.z
          add r5.x, r5.x, cb0[122].w
          mad r1.xyz, r5.xxxx, r1.xyzx, r2.xyzx
          mov_sat r5.x, r5.x
          sample r6.xyzw, r3.yzyy, t0.xyzw, s0
          mul_sat r2.x, r3.w, l(50.000050)
          mad r3.yzw, r6.xxyz, v3.xxyz, -cb2[6].xxyz
          mul r6.xyzw, r6.xyzw, v3.xyzw
          mad r3.yzw, cb2[5].yyyy, r3.yyzw, cb2[6].xxyz
          mad r0.xyz, -r3.yzwy, r1.xyzx, r0.xyzx
          mul r1.xyz, r1.xyzx, r3.yzwy
          log r2.y, r4.z
          add r2.z, r4.z, -r5.x
          mul r2.y, r2.y, cb2[5].x
          exp r2.y, r2.y
          mul r2.y, r2.y, cb0[126].w
          mad r0.xyz, r2.yyyy, r0.xyzx, r1.xyzx
          mov r4.zw, l(0,0,1.000000,0.001000)
          dp3 r1.x, r4.xywx, r4.xywx
          rsq r1.x, r1.x
          mul r1.xyz, r1.xxxx, r4.xywx
          mad r2.y, r2.x, l(-2.000000), l(3.000000)
          mul r2.x, r2.x, r2.x
          dp2 r2.x, r2.yyyy, r2.xxxx
          add r2.x, r2.x, l(-1.000000)
          mul r2.x, r2.x, cb2[7].x
          add r2.y, -cb2[7].x, l(1.000000)
          dp2 r3.y, r2.xyxx, r2.xyxx
          rsq r3.y, r3.y
          mul r4.xy, r2.xyxx, r3.yyyy
          dp3 r7.x, r4.xyzx, cb1[4].xzwx
          dp3 r7.y, r4.xyzx, cb1[5].xzwx
          dp3 r7.z, r4.xyzx, cb1[6].xzwx
          dp3 r1.x, r7.xyzx, r1.xyzx
          add r1.x, r1.x, l(1.000000)
          mad r3.yzw, -r1.xxxx, r6.xxyz, r0.xxyz
          mul r1.xyz, r6.xyzx, r1.xxxx
          mov o0.w, r6.w
          mad r1.xyz, r2.wwww, r3.yzwy, r1.xyzx
          log r2.xyw, |cb2[3].xyxz|
          mul r2.xyw, r2.xyxw, l(0.416667, 0.416667, 0.000000, 0.416667)
          exp r2.xyw, r2.xyxw
          mad r2.xyw, r2.xyxw, l(1.055000, 1.055000, 0.000000, 1.055000), l(-0.055000, -0.055000, 0.000000, -0.055000)
          mul r3.yzw, cb2[3].xxyz, l(0.000000, 12.920000, 12.920000, 12.920000)
          ge r4.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb2[3].xyzx
          movc r2.xyw, r4.xyxz, r3.yzyw, r2.xyxw
          add r2.xyw, -r1.xyxz, r2.xyxw
          mad r1.xyz, cb2[2].yyyy, r2.xywx, r1.xyzx
          add r2.xyw, r1.xyxz, -cb0[129].xyxz
          add r3.yz, v1.xxyx, -cb2[12].xxyx
          dp2 r3.y, r3.yzyy, cb2[12].zwzz
          mul r1.w, r1.w, r3.y
          mul r1.w, r1.w, cb2[13].z
          mad r1.w, r3.x, cb2[13].y, r1.w
          mul r3.x, r0.w, r1.w
          mad r0.w, r1.w, r0.w, l(1.000000)
          ge r1.w, r1.w, l(0.000000)
          and r1.w, r1.w, l(0x3f800000)
          mul r3.x, r3.x, l(1.442695)
          exp r3.x, r3.x
          mad r2.xyw, r3.xxxx, r2.xyxw, cb0[129].xyxz
          mad r1.xyz, r1.xyzx, r0.wwww, -r2.xywx
          mad r1.xyz, r1.wwww, r1.xyzx, r2.xywx
          ge r2.xyw, cb0[130].xxxx, l(2.500000, 1.500000, 0.000000, 0.500000)
          and r2.xyw, r2.xyxw, l(0x3f800000, 0x3f800000, 0, 0x3f800000)
          mad r0.w, r2.x, r2.z, r5.x
          add r3.xyz, -r0.xyzx, r0.wwww
          mad r0.xyz, r2.yyyy, r3.xyzx, r0.xyzx
          dp3 r0.x, r0.xyzx, l(0.212673, 0.715152, 0.072175, 0.000000)
          add r0.xyz, -r1.xyzx, r0.xxxx
          mad o0.xyz, r2.wwww, r0.xyzx, r1.xyzx
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 2, name: DepthOnly
    {
      Name "DepthOnly"
      Tags
      { 
        "LIGHTMODE" = "DepthOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      ColorMask 0
      GpuProgramID 329531
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyzw        1     NONE   float   xyzw
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyzw
          dcl_output o2.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r0.xyzw, cb0[72].xyzw
          mov o1.xyzw, v3.xyzw
          mov o2.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyzw        1     NONE   float       
          // TEXCOORD                 1   xyzw        2     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_output o0.xyzw
          mov o0.xyzw, l(0,0,0,0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  FallBack "Hidden/Shader Graph/FallbackError"
}
