Shader "Shader Graphs/PlayerLQTrail"
{
  Properties
  {
    _NoiseTilingMutationSmoothEdge ("Noise Params", Vector) = (2,1,0.2,0.1)
    Color_f200eb8a198a431fbc2af5946ec4f9d7 ("Main Color", Color) = (0,0,0,0)
    [HDR] Color_f200eb8a198a431fbc2af5946ec4f9d7_1 ("Edge Color", Color) = (4,4,4,0)
    unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" {}
    unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" {}
    unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" {}
  }
  SubShader
  {
    Tags
    { 
      "QUEUE" = "Transparent"
      "RenderPipeline" = "UniversalPipeline"
      "RenderType" = "Transparent"
      "UniversalMaterialType" = "Unlit"
    }
    Pass // ind: 1, name: Pass
    {
      Name "Pass"
      Tags
      { 
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      GpuProgramID 37206
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyz         1     NONE   float   xyz 
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[72].xyzw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
        SubProgram "vulkan"
        {
          
          "!!vulkan
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyz         1     NONE   float   xy  
          // TEXCOORD                 1   xyzw        2     NONE   float   xy  
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[13], immediateIndexed
          dcl_constantbuffer CB1[3], immediateIndexed
          dcl_input_ps linear v1.xy
          dcl_input_ps linear v2.xy
          dcl_input_ps linear v3.xyzw
          dcl_output o0.xyzw
          dcl_temps 5
          mad r0.xy, cb1[0].yyyy, cb0[12].xxxx, v1.xyxx
          mul r0.xy, r0.xyxx, cb1[0].xxxx
          round_ni r0.zw, r0.xxxy
          frc r0.xy, r0.xyxx
          add r1.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
          mul r2.xyzw, r1.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r2.xyzw, r2.xyzw, -r2.zwzw
          movc r2.xyzw, r2.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.xy, r1.xyxx, r2.zwzz
          frc r1.xy, r1.xyxx
          mul r1.xy, r1.xyxx, r2.xyxx
          mad r1.z, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.z
          mul r1.z, r1.x, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.x, r1.w, r1.x
          frc r1.x, r1.x
          mad r1.x, r1.z, r1.x, r1.y
          mad r1.y, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.y
          mul r1.y, r1.x, l(289.000000)
          ge r1.y, r1.y, -r1.y
          movc r1.yz, r1.yyyy, l(0,289.000000,0.003460,0), l(0,-289.000000,-0.003460,0)
          mul r1.x, r1.z, r1.x
          frc r1.x, r1.x
          mul r1.x, r1.x, r1.y
          mul r1.x, r1.x, l(0.024390)
          frc r1.x, r1.x
          mad r1.xy, r1.xxxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
          round_ni r1.y, r1.y
          add r2.x, -r1.y, r1.x
          add r2.y, |r1.x|, l(-0.500000)
          dp2 r1.x, r2.xyxx, r2.xyxx
          rsq r1.x, r1.x
          mul r1.xy, r1.xxxx, r2.xyxx
          add r1.zw, r0.xxxy, l(0.000000, 0.000000, -1.000000, -1.000000)
          dp2 r1.x, r1.xyxx, r1.zwzz
          add r2.xyzw, r0.zwzw, l(0.000000, 1.000000, 1.000000, 0.000000)
          mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r3.xyzw, r3.xyzw, -r3.xyzw
          movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.yz, r2.zzwz, r4.zzwz
          mul r2.xy, r2.xyxx, r3.zwzz
          frc r2.xy, r2.xyxx
          mul r2.xy, r2.xyxx, r3.xyxx
          frc r1.yz, r1.yyzy
          mul r1.yz, r1.yyzy, r4.xxyx
          mad r1.w, r1.y, l(34.000000), l(1.000000)
          mul r1.y, r1.y, r1.w
          mul r1.w, r1.y, l(289.000000)
          ge r1.w, r1.w, -r1.w
          movc r2.zw, r1.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.y, r1.y, r2.w
          frc r1.y, r1.y
          mad r1.y, r2.z, r1.y, r1.z
          mad r1.z, r1.y, l(34.000000), l(1.000000)
          mul r1.y, r1.y, r1.z
          mul r1.z, r1.y, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.y, r1.w, r1.y
          frc r1.y, r1.y
          mul r1.y, r1.y, r1.z
          mul r1.y, r1.y, l(0.024390)
          frc r1.y, r1.y
          mad r1.yz, r1.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
          round_ni r1.z, r1.z
          add r3.x, -r1.z, r1.y
          add r3.y, |r1.y|, l(-0.500000)
          dp2 r1.y, r3.xyxx, r3.xyxx
          rsq r1.y, r1.y
          mul r1.yz, r1.yyyy, r3.xxyx
          add r3.xyzw, r0.xyxy, l(-0.000000, -1.000000, -1.000000, -0.000000)
          dp2 r1.y, r1.yzyy, r3.zwzz
          add r1.x, -r1.y, r1.x
          mul r1.zw, r0.xxxy, r0.xxxy
          mul r1.zw, r0.xxxy, r1.zzzw
          mad r2.zw, r0.xxxy, l(0.000000, 0.000000, 6.000000, 6.000000), l(0.000000, 0.000000, -15.000000, -15.000000)
          mad r2.zw, r0.xxxy, r2.zzzw, l(0.000000, 0.000000, 10.000000, 10.000000)
          mul r1.zw, r1.zzzw, r2.zzzw
          mad r1.x, r1.w, r1.x, r1.y
          mul r4.xyzw, r0.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r4.xyzw, r4.xyzw, -r4.zwzw
          movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r0.zw, r0.zzzw, r4.zzzw
          frc r0.zw, r0.zzzw
          mul r0.zw, r0.zzzw, r4.xxxy
          mad r1.y, r0.z, l(34.000000), l(1.000000)
          mul r0.z, r0.z, r1.y
          mul r1.y, r0.z, l(289.000000)
          ge r1.y, r1.y, -r1.y
          movc r2.zw, r1.yyyy, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.z, r0.z, r2.w
          frc r0.z, r0.z
          mad r0.z, r2.z, r0.z, r0.w
          mad r0.w, r0.z, l(34.000000), l(1.000000)
          mul r0.z, r0.z, r0.w
          mul r0.w, r0.z, l(289.000000)
          ge r0.w, r0.w, -r0.w
          movc r2.zw, r0.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.z, r0.z, r2.w
          frc r0.z, r0.z
          mul r0.z, r0.z, r2.z
          mul r0.z, r0.z, l(0.024390)
          frc r0.z, r0.z
          mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
          round_ni r0.w, r0.w
          add r4.x, -r0.w, r0.z
          add r4.y, |r0.z|, l(-0.500000)
          dp2 r0.z, r4.xyxx, r4.xyxx
          rsq r0.z, r0.z
          mul r0.zw, r0.zzzz, r4.xxxy
          dp2 r0.x, r0.zwzz, r0.xyxx
          mad r0.y, r2.x, l(34.000000), l(1.000000)
          mul r0.y, r2.x, r0.y
          mul r0.z, r0.y, l(289.000000)
          ge r0.z, r0.z, -r0.z
          movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.y, r0.w, r0.y
          frc r0.y, r0.y
          mad r0.y, r0.z, r0.y, r2.y
          mad r0.z, r0.y, l(34.000000), l(1.000000)
          mul r0.y, r0.y, r0.z
          mul r0.z, r0.y, l(289.000000)
          ge r0.z, r0.z, -r0.z
          movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.y, r0.w, r0.y
          frc r0.y, r0.y
          mul r0.y, r0.y, r0.z
          mul r0.y, r0.y, l(0.024390)
          frc r0.y, r0.y
          mad r0.yz, r0.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
          round_ni r0.z, r0.z
          add r2.x, -r0.z, r0.y
          add r2.y, |r0.y|, l(-0.500000)
          dp2 r0.y, r2.xyxx, r2.xyxx
          rsq r0.y, r0.y
          mul r0.yz, r0.yyyy, r2.xxyx
          dp2 r0.y, r0.yzyy, r3.xyxx
          add r0.y, -r0.x, r0.y
          mad r0.x, r1.w, r0.y, r0.x
          add r0.y, -r0.x, r1.x
          mad r0.x, r1.z, r0.y, r0.x
          add r0.x, r0.x, l(0.500000)
          mad r0.yz, -cb1[0].yyyy, cb0[12].xxxx, v1.xxyx
          mul r0.yz, r0.yyzy, cb1[0].xxxx
          round_ni r1.xy, r0.yzyy
          add r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
          mul r2.xyzw, r1.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r2.xyzw, r2.xyzw, -r2.zwzw
          movc r2.xyzw, r2.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.zw, r1.zzzw, r2.zzzw
          frc r1.zw, r1.zzzw
          mul r1.zw, r1.zzzw, r2.xxxy
          mad r0.w, r1.z, l(34.000000), l(1.000000)
          mul r0.w, r1.z, r0.w
          mul r1.z, r0.w, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r2.xy, r1.zzzz, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
          mul r0.w, r0.w, r2.y
          frc r0.yzw, r0.yyzw
          mad r0.w, r2.x, r0.w, r1.w
          mad r1.z, r0.w, l(34.000000), l(1.000000)
          mul r0.w, r0.w, r1.z
          mul r1.z, r0.w, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.w, r0.w, r1.w
          frc r0.w, r0.w
          mul r0.w, r0.w, r1.z
          mul r0.w, r0.w, l(0.024390)
          frc r0.w, r0.w
          mad r1.zw, r0.wwww, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
          round_ni r0.w, r1.w
          add r2.x, -r0.w, r1.z
          add r2.y, |r1.z|, l(-0.500000)
          dp2 r0.w, r2.xyxx, r2.xyxx
          rsq r0.w, r0.w
          mul r1.zw, r0.wwww, r2.xxxy
          add r2.xy, r0.yzyy, l(-1.000000, -1.000000, 0.000000, 0.000000)
          dp2 r0.w, r1.zwzz, r2.xyxx
          add r2.xyzw, r1.xyxy, l(0.000000, 1.000000, 1.000000, 0.000000)
          mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r3.xyzw, r3.xyzw, -r3.xyzw
          movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.zw, r2.zzzw, r4.zzzw
          mul r2.xy, r2.xyxx, r3.zwzz
          frc r2.xy, r2.xyxx
          mul r2.xy, r2.xyxx, r3.xyxx
          frc r1.zw, r1.zzzw
          mul r1.zw, r1.zzzw, r4.xxxy
          mad r2.z, r1.z, l(34.000000), l(1.000000)
          mul r1.z, r1.z, r2.z
          mul r2.z, r1.z, l(289.000000)
          ge r2.z, r2.z, -r2.z
          movc r2.zw, r2.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.z, r1.z, r2.w
          frc r1.z, r1.z
          mad r1.z, r2.z, r1.z, r1.w
          mad r1.w, r1.z, l(34.000000), l(1.000000)
          mul r1.z, r1.z, r1.w
          mul r1.w, r1.z, l(289.000000)
          ge r1.w, r1.w, -r1.w
          movc r2.zw, r1.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.z, r1.z, r2.w
          frc r1.z, r1.z
          mul r1.z, r1.z, r2.z
          mul r1.z, r1.z, l(0.024390)
          frc r1.z, r1.z
          mad r1.zw, r1.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
          round_ni r1.w, r1.w
          add r3.x, -r1.w, r1.z
          add r3.y, |r1.z|, l(-0.500000)
          dp2 r1.z, r3.xyxx, r3.xyxx
          rsq r1.z, r1.z
          mul r1.zw, r1.zzzz, r3.xxxy
          add r3.xyzw, r0.yzyz, l(-0.000000, -1.000000, -1.000000, -0.000000)
          dp2 r1.z, r1.zwzz, r3.zwzz
          add r0.w, r0.w, -r1.z
          mul r2.zw, r0.yyyz, r0.yyyz
          mul r2.zw, r0.yyyz, r2.zzzw
          mad r3.zw, r0.yyyz, l(0.000000, 0.000000, 6.000000, 6.000000), l(0.000000, 0.000000, -15.000000, -15.000000)
          mad r3.zw, r0.yyyz, r3.zzzw, l(0.000000, 0.000000, 10.000000, 10.000000)
          mul r2.zw, r2.zzzw, r3.zzzw
          mad r0.w, r2.w, r0.w, r1.z
          mul r4.xyzw, r1.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r4.xyzw, r4.xyzw, -r4.zwzw
          movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.xy, r1.xyxx, r4.zwzz
          frc r1.xy, r1.xyxx
          mul r1.xy, r1.xyxx, r4.xyxx
          mad r1.z, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.z
          mul r1.z, r1.x, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.x, r1.w, r1.x
          frc r1.x, r1.x
          mad r1.x, r1.z, r1.x, r1.y
          mad r1.y, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.y
          mul r1.y, r1.x, l(289.000000)
          ge r1.y, r1.y, -r1.y
          movc r1.yz, r1.yyyy, l(0,289.000000,0.003460,0), l(0,-289.000000,-0.003460,0)
          mul r1.x, r1.z, r1.x
          frc r1.x, r1.x
          mul r1.x, r1.x, r1.y
          mul r1.x, r1.x, l(0.024390)
          frc r1.x, r1.x
          mad r1.xy, r1.xxxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
          round_ni r1.y, r1.y
          add r4.x, -r1.y, r1.x
          add r4.y, |r1.x|, l(-0.500000)
          dp2 r1.x, r4.xyxx, r4.xyxx
          rsq r1.x, r1.x
          mul r1.xy, r1.xxxx, r4.xyxx
          dp2 r0.y, r1.xyxx, r0.yzyy
          mad r0.z, r2.x, l(34.000000), l(1.000000)
          mul r0.z, r2.x, r0.z
          mul r1.x, r0.z, l(289.000000)
          ge r1.x, r1.x, -r1.x
          movc r1.xy, r1.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
          mul r0.z, r0.z, r1.y
          frc r0.z, r0.z
          mad r0.z, r1.x, r0.z, r2.y
          mad r1.x, r0.z, l(34.000000), l(1.000000)
          mul r0.z, r0.z, r1.x
          mul r1.x, r0.z, l(289.000000)
          ge r1.x, r1.x, -r1.x
          movc r1.xy, r1.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
          mul r0.z, r0.z, r1.y
          frc r0.z, r0.z
          mul r0.z, r0.z, r1.x
          mul r0.z, r0.z, l(0.024390)
          frc r0.z, r0.z
          mad r1.xy, r0.zzzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
          round_ni r0.z, r1.y
          add r2.x, -r0.z, r1.x
          add r2.y, |r1.x|, l(-0.500000)
          dp2 r0.z, r2.xyxx, r2.xyxx
          rsq r0.z, r0.z
          mul r1.xy, r0.zzzz, r2.xyxx
          dp2 r0.z, r1.xyxx, r3.xyxx
          add r0.z, -r0.y, r0.z
          mad r0.y, r2.w, r0.z, r0.y
          add r0.z, -r0.y, r0.w
          mad r0.y, r2.z, r0.z, r0.y
          add r0.x, r0.x, r0.y
          add r0.x, r0.x, l(0.500000)
          mul r0.y, r0.x, l(0.500000)
          mad r0.z, -v2.y, l(2.000000), l(1.000000)
          mad r0.y, cb1[0].w, r0.y, |r0.z|
          add r0.y, -r0.y, l(1.000000)
          div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[0].z
          mul_sat r0.y, r0.z, r0.y
          mad r0.z, r0.y, l(-2.000000), l(3.000000)
          mul r0.y, r0.y, r0.y
          mul r0.y, r0.y, r0.z
          add r0.z, v2.x, -cb1[0].z
          mad r0.x, r0.x, l(0.500000), -r0.z
          add r0.w, v2.x, cb1[0].z
          add r0.z, -r0.z, r0.w
          div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
          mul_sat r0.x, r0.z, r0.x
          mad r0.z, r0.x, l(-2.000000), l(3.000000)
          mul r0.x, r0.x, r0.x
          mul r0.x, r0.x, r0.z
          mul r0.x, r0.x, r0.y
          log r0.yzw, |cb1[2].xxyz|
          mul r0.yzw, r0.yyzw, l(0.000000, 0.416667, 0.416667, 0.416667)
          exp r0.yzw, r0.yyzw
          mad r0.yzw, r0.yyzw, l(0.000000, 1.055000, 1.055000, 1.055000), l(0.000000, -0.055000, -0.055000, -0.055000)
          mul r1.xyz, cb1[2].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb1[2].xyzx
          movc r0.yzw, r2.xxyz, r1.xxyz, r0.yyzw
          add r1.xyz, -r0.yzwy, cb1[1].xyzx
          mad r0.yzw, r0.xxxx, r1.xxyz, r0.yyzw
          mul o0.w, r0.x, v3.w
          mul o0.xyz, r0.yzwy, v3.xyzx
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 2, name: DepthOnly
    {
      Name "DepthOnly"
      Tags
      { 
        "LIGHTMODE" = "DepthOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      ColorMask 0
      GpuProgramID 160649
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyz         1     NONE   float   xyz 
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[72].xyzw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
        SubProgram "vulkan"
        {
          
          "!!vulkan
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyz         1     NONE   float       
          // TEXCOORD                 1   xyzw        2     NONE   float       
          // TEXCOORD                 2   xyzw        3     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_output o0.xyzw
          mov o0.xyzw, l(0,0,0,0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  SubShader
  {
    Tags
    { 
      "QUEUE" = "Transparent"
      "RenderPipeline" = "UniversalPipeline"
      "RenderType" = "Transparent"
      "UniversalMaterialType" = "Unlit"
    }
    Pass // ind: 1, name: Pass
    {
      Name "Pass"
      Tags
      { 
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      GpuProgramID 235044
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyz         1     NONE   float   xyz 
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[72].xyzw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyz         1     NONE   float   xy  
          // TEXCOORD                 1   xyzw        2     NONE   float   xy  
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_constantbuffer CB0[13], immediateIndexed
          dcl_constantbuffer CB1[3], immediateIndexed
          dcl_input_ps linear v1.xy
          dcl_input_ps linear v2.xy
          dcl_input_ps linear v3.xyzw
          dcl_output o0.xyzw
          dcl_temps 5
          mad r0.xy, cb1[0].yyyy, cb0[12].xxxx, v1.xyxx
          mul r0.xy, r0.xyxx, cb1[0].xxxx
          round_ni r0.zw, r0.xxxy
          frc r0.xy, r0.xyxx
          add r1.xy, r0.zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
          mul r2.xyzw, r1.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r2.xyzw, r2.xyzw, -r2.zwzw
          movc r2.xyzw, r2.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.xy, r1.xyxx, r2.zwzz
          frc r1.xy, r1.xyxx
          mul r1.xy, r1.xyxx, r2.xyxx
          mad r1.z, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.z
          mul r1.z, r1.x, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.x, r1.w, r1.x
          frc r1.x, r1.x
          mad r1.x, r1.z, r1.x, r1.y
          mad r1.y, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.y
          mul r1.y, r1.x, l(289.000000)
          ge r1.y, r1.y, -r1.y
          movc r1.yz, r1.yyyy, l(0,289.000000,0.003460,0), l(0,-289.000000,-0.003460,0)
          mul r1.x, r1.z, r1.x
          frc r1.x, r1.x
          mul r1.x, r1.x, r1.y
          mul r1.x, r1.x, l(0.024390)
          frc r1.x, r1.x
          mad r1.xy, r1.xxxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
          round_ni r1.y, r1.y
          add r2.x, -r1.y, r1.x
          add r2.y, |r1.x|, l(-0.500000)
          dp2 r1.x, r2.xyxx, r2.xyxx
          rsq r1.x, r1.x
          mul r1.xy, r1.xxxx, r2.xyxx
          add r1.zw, r0.xxxy, l(0.000000, 0.000000, -1.000000, -1.000000)
          dp2 r1.x, r1.xyxx, r1.zwzz
          add r2.xyzw, r0.zwzw, l(0.000000, 1.000000, 1.000000, 0.000000)
          mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r3.xyzw, r3.xyzw, -r3.xyzw
          movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.yz, r2.zzwz, r4.zzwz
          mul r2.xy, r2.xyxx, r3.zwzz
          frc r2.xy, r2.xyxx
          mul r2.xy, r2.xyxx, r3.xyxx
          frc r1.yz, r1.yyzy
          mul r1.yz, r1.yyzy, r4.xxyx
          mad r1.w, r1.y, l(34.000000), l(1.000000)
          mul r1.y, r1.y, r1.w
          mul r1.w, r1.y, l(289.000000)
          ge r1.w, r1.w, -r1.w
          movc r2.zw, r1.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.y, r1.y, r2.w
          frc r1.y, r1.y
          mad r1.y, r2.z, r1.y, r1.z
          mad r1.z, r1.y, l(34.000000), l(1.000000)
          mul r1.y, r1.y, r1.z
          mul r1.z, r1.y, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.y, r1.w, r1.y
          frc r1.y, r1.y
          mul r1.y, r1.y, r1.z
          mul r1.y, r1.y, l(0.024390)
          frc r1.y, r1.y
          mad r1.yz, r1.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
          round_ni r1.z, r1.z
          add r3.x, -r1.z, r1.y
          add r3.y, |r1.y|, l(-0.500000)
          dp2 r1.y, r3.xyxx, r3.xyxx
          rsq r1.y, r1.y
          mul r1.yz, r1.yyyy, r3.xxyx
          add r3.xyzw, r0.xyxy, l(-0.000000, -1.000000, -1.000000, -0.000000)
          dp2 r1.y, r1.yzyy, r3.zwzz
          add r1.x, -r1.y, r1.x
          mul r1.zw, r0.xxxy, r0.xxxy
          mul r1.zw, r0.xxxy, r1.zzzw
          mad r2.zw, r0.xxxy, l(0.000000, 0.000000, 6.000000, 6.000000), l(0.000000, 0.000000, -15.000000, -15.000000)
          mad r2.zw, r0.xxxy, r2.zzzw, l(0.000000, 0.000000, 10.000000, 10.000000)
          mul r1.zw, r1.zzzw, r2.zzzw
          mad r1.x, r1.w, r1.x, r1.y
          mul r4.xyzw, r0.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r4.xyzw, r4.xyzw, -r4.zwzw
          movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r0.zw, r0.zzzw, r4.zzzw
          frc r0.zw, r0.zzzw
          mul r0.zw, r0.zzzw, r4.xxxy
          mad r1.y, r0.z, l(34.000000), l(1.000000)
          mul r0.z, r0.z, r1.y
          mul r1.y, r0.z, l(289.000000)
          ge r1.y, r1.y, -r1.y
          movc r2.zw, r1.yyyy, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.z, r0.z, r2.w
          frc r0.z, r0.z
          mad r0.z, r2.z, r0.z, r0.w
          mad r0.w, r0.z, l(34.000000), l(1.000000)
          mul r0.z, r0.z, r0.w
          mul r0.w, r0.z, l(289.000000)
          ge r0.w, r0.w, -r0.w
          movc r2.zw, r0.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.z, r0.z, r2.w
          frc r0.z, r0.z
          mul r0.z, r0.z, r2.z
          mul r0.z, r0.z, l(0.024390)
          frc r0.z, r0.z
          mad r0.zw, r0.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
          round_ni r0.w, r0.w
          add r4.x, -r0.w, r0.z
          add r4.y, |r0.z|, l(-0.500000)
          dp2 r0.z, r4.xyxx, r4.xyxx
          rsq r0.z, r0.z
          mul r0.zw, r0.zzzz, r4.xxxy
          dp2 r0.x, r0.zwzz, r0.xyxx
          mad r0.y, r2.x, l(34.000000), l(1.000000)
          mul r0.y, r2.x, r0.y
          mul r0.z, r0.y, l(289.000000)
          ge r0.z, r0.z, -r0.z
          movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.y, r0.w, r0.y
          frc r0.y, r0.y
          mad r0.y, r0.z, r0.y, r2.y
          mad r0.z, r0.y, l(34.000000), l(1.000000)
          mul r0.y, r0.y, r0.z
          mul r0.z, r0.y, l(289.000000)
          ge r0.z, r0.z, -r0.z
          movc r0.zw, r0.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.y, r0.w, r0.y
          frc r0.y, r0.y
          mul r0.y, r0.y, r0.z
          mul r0.y, r0.y, l(0.024390)
          frc r0.y, r0.y
          mad r0.yz, r0.yyyy, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -0.500000, 0.000000)
          round_ni r0.z, r0.z
          add r2.x, -r0.z, r0.y
          add r2.y, |r0.y|, l(-0.500000)
          dp2 r0.y, r2.xyxx, r2.xyxx
          rsq r0.y, r0.y
          mul r0.yz, r0.yyyy, r2.xxyx
          dp2 r0.y, r0.yzyy, r3.xyxx
          add r0.y, -r0.x, r0.y
          mad r0.x, r1.w, r0.y, r0.x
          add r0.y, -r0.x, r1.x
          mad r0.x, r1.z, r0.y, r0.x
          add r0.x, r0.x, l(0.500000)
          mad r0.yz, -cb1[0].yyyy, cb0[12].xxxx, v1.xxyx
          mul r0.yz, r0.yyzy, cb1[0].xxxx
          round_ni r1.xy, r0.yzyy
          add r1.zw, r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
          mul r2.xyzw, r1.zwzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r2.xyzw, r2.xyzw, -r2.zwzw
          movc r2.xyzw, r2.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.zw, r1.zzzw, r2.zzzw
          frc r1.zw, r1.zzzw
          mul r1.zw, r1.zzzw, r2.xxxy
          mad r0.w, r1.z, l(34.000000), l(1.000000)
          mul r0.w, r1.z, r0.w
          mul r1.z, r0.w, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r2.xy, r1.zzzz, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
          mul r0.w, r0.w, r2.y
          frc r0.yzw, r0.yyzw
          mad r0.w, r2.x, r0.w, r1.w
          mad r1.z, r0.w, l(34.000000), l(1.000000)
          mul r0.w, r0.w, r1.z
          mul r1.z, r0.w, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r0.w, r0.w, r1.w
          frc r0.w, r0.w
          mul r0.w, r0.w, r1.z
          mul r0.w, r0.w, l(0.024390)
          frc r0.w, r0.w
          mad r1.zw, r0.wwww, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
          round_ni r0.w, r1.w
          add r2.x, -r0.w, r1.z
          add r2.y, |r1.z|, l(-0.500000)
          dp2 r0.w, r2.xyxx, r2.xyxx
          rsq r0.w, r0.w
          mul r1.zw, r0.wwww, r2.xxxy
          add r2.xy, r0.yzyy, l(-1.000000, -1.000000, 0.000000, 0.000000)
          dp2 r0.w, r1.zwzz, r2.xyxx
          add r2.xyzw, r1.xyxy, l(0.000000, 1.000000, 1.000000, 0.000000)
          mul r3.xyzw, r2.xyzw, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r3.xyzw, r3.xyzw, -r3.xyzw
          movc r4.xyzw, r3.zwzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          movc r3.xyzw, r3.xyxy, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.zw, r2.zzzw, r4.zzzw
          mul r2.xy, r2.xyxx, r3.zwzz
          frc r2.xy, r2.xyxx
          mul r2.xy, r2.xyxx, r3.xyxx
          frc r1.zw, r1.zzzw
          mul r1.zw, r1.zzzw, r4.xxxy
          mad r2.z, r1.z, l(34.000000), l(1.000000)
          mul r1.z, r1.z, r2.z
          mul r2.z, r1.z, l(289.000000)
          ge r2.z, r2.z, -r2.z
          movc r2.zw, r2.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.z, r1.z, r2.w
          frc r1.z, r1.z
          mad r1.z, r2.z, r1.z, r1.w
          mad r1.w, r1.z, l(34.000000), l(1.000000)
          mul r1.z, r1.z, r1.w
          mul r1.w, r1.z, l(289.000000)
          ge r1.w, r1.w, -r1.w
          movc r2.zw, r1.wwww, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.z, r1.z, r2.w
          frc r1.z, r1.z
          mul r1.z, r1.z, r2.z
          mul r1.z, r1.z, l(0.024390)
          frc r1.z, r1.z
          mad r1.zw, r1.zzzz, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -0.500000)
          round_ni r1.w, r1.w
          add r3.x, -r1.w, r1.z
          add r3.y, |r1.z|, l(-0.500000)
          dp2 r1.z, r3.xyxx, r3.xyxx
          rsq r1.z, r1.z
          mul r1.zw, r1.zzzz, r3.xxxy
          add r3.xyzw, r0.yzyz, l(-0.000000, -1.000000, -1.000000, -0.000000)
          dp2 r1.z, r1.zwzz, r3.zwzz
          add r0.w, r0.w, -r1.z
          mul r2.zw, r0.yyyz, r0.yyyz
          mul r2.zw, r0.yyyz, r2.zzzw
          mad r3.zw, r0.yyyz, l(0.000000, 0.000000, 6.000000, 6.000000), l(0.000000, 0.000000, -15.000000, -15.000000)
          mad r3.zw, r0.yyyz, r3.zzzw, l(0.000000, 0.000000, 10.000000, 10.000000)
          mul r2.zw, r2.zzzw, r3.zzzw
          mad r0.w, r2.w, r0.w, r1.z
          mul r4.xyzw, r1.xyxy, l(289.000000, 289.000000, 289.000000, 289.000000)
          ge r4.xyzw, r4.xyzw, -r4.zwzw
          movc r4.xyzw, r4.xyzw, l(289.000000,289.000000,0.003460,0.003460), l(-289.000000,-289.000000,-0.003460,-0.003460)
          mul r1.xy, r1.xyxx, r4.zwzz
          frc r1.xy, r1.xyxx
          mul r1.xy, r1.xyxx, r4.xyxx
          mad r1.z, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.z
          mul r1.z, r1.x, l(289.000000)
          ge r1.z, r1.z, -r1.z
          movc r1.zw, r1.zzzz, l(0,0,289.000000,0.003460), l(0,0,-289.000000,-0.003460)
          mul r1.x, r1.w, r1.x
          frc r1.x, r1.x
          mad r1.x, r1.z, r1.x, r1.y
          mad r1.y, r1.x, l(34.000000), l(1.000000)
          mul r1.x, r1.x, r1.y
          mul r1.y, r1.x, l(289.000000)
          ge r1.y, r1.y, -r1.y
          movc r1.yz, r1.yyyy, l(0,289.000000,0.003460,0), l(0,-289.000000,-0.003460,0)
          mul r1.x, r1.z, r1.x
          frc r1.x, r1.x
          mul r1.x, r1.x, r1.y
          mul r1.x, r1.x, l(0.024390)
          frc r1.x, r1.x
          mad r1.xy, r1.xxxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
          round_ni r1.y, r1.y
          add r4.x, -r1.y, r1.x
          add r4.y, |r1.x|, l(-0.500000)
          dp2 r1.x, r4.xyxx, r4.xyxx
          rsq r1.x, r1.x
          mul r1.xy, r1.xxxx, r4.xyxx
          dp2 r0.y, r1.xyxx, r0.yzyy
          mad r0.z, r2.x, l(34.000000), l(1.000000)
          mul r0.z, r2.x, r0.z
          mul r1.x, r0.z, l(289.000000)
          ge r1.x, r1.x, -r1.x
          movc r1.xy, r1.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
          mul r0.z, r0.z, r1.y
          frc r0.z, r0.z
          mad r0.z, r1.x, r0.z, r2.y
          mad r1.x, r0.z, l(34.000000), l(1.000000)
          mul r0.z, r0.z, r1.x
          mul r1.x, r0.z, l(289.000000)
          ge r1.x, r1.x, -r1.x
          movc r1.xy, r1.xxxx, l(289.000000,0.003460,0,0), l(-289.000000,-0.003460,0,0)
          mul r0.z, r0.z, r1.y
          frc r0.z, r0.z
          mul r0.z, r0.z, r1.x
          mul r0.z, r0.z, l(0.024390)
          frc r0.z, r0.z
          mad r1.xy, r0.zzzz, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -0.500000, 0.000000, 0.000000)
          round_ni r0.z, r1.y
          add r2.x, -r0.z, r1.x
          add r2.y, |r1.x|, l(-0.500000)
          dp2 r0.z, r2.xyxx, r2.xyxx
          rsq r0.z, r0.z
          mul r1.xy, r0.zzzz, r2.xyxx
          dp2 r0.z, r1.xyxx, r3.xyxx
          add r0.z, -r0.y, r0.z
          mad r0.y, r2.w, r0.z, r0.y
          add r0.z, -r0.y, r0.w
          mad r0.y, r2.z, r0.z, r0.y
          add r0.x, r0.x, r0.y
          add r0.x, r0.x, l(0.500000)
          mul r0.y, r0.x, l(0.500000)
          mad r0.z, -v2.y, l(2.000000), l(1.000000)
          mad r0.y, cb1[0].w, r0.y, |r0.z|
          add r0.y, -r0.y, l(1.000000)
          div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), cb1[0].z
          mul_sat r0.y, r0.z, r0.y
          mad r0.z, r0.y, l(-2.000000), l(3.000000)
          mul r0.y, r0.y, r0.y
          mul r0.y, r0.y, r0.z
          add r0.z, v2.x, -cb1[0].z
          mad r0.x, r0.x, l(0.500000), -r0.z
          add r0.w, v2.x, cb1[0].z
          add r0.z, -r0.z, r0.w
          div r0.z, l(1.000000, 1.000000, 1.000000, 1.000000), r0.z
          mul_sat r0.x, r0.z, r0.x
          mad r0.z, r0.x, l(-2.000000), l(3.000000)
          mul r0.x, r0.x, r0.x
          mul r0.x, r0.x, r0.z
          mul r0.x, r0.x, r0.y
          log r0.yzw, |cb1[2].xxyz|
          mul r0.yzw, r0.yyzw, l(0.000000, 0.416667, 0.416667, 0.416667)
          exp r0.yzw, r0.yyzw
          mad r0.yzw, r0.yyzw, l(0.000000, 1.055000, 1.055000, 1.055000), l(0.000000, -0.055000, -0.055000, -0.055000)
          mul r1.xyz, cb1[2].xyzx, l(12.920000, 12.920000, 12.920000, 0.000000)
          ge r2.xyz, l(0.003131, 0.003131, 0.003131, 0.000000), cb1[2].xyzx
          movc r0.yzw, r2.xxyz, r1.xxyz, r0.yyzw
          add r1.xyz, -r0.yzwy, cb1[1].xyzx
          mad r0.yzw, r0.xxxx, r1.xxyz, r0.yyzw
          mul o0.w, r0.x, v3.w
          mul o0.xyz, r0.yzwy, v3.xyzx
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 2, name: DepthOnly
    {
      Name "DepthOnly"
      Tags
      { 
        "LIGHTMODE" = "DepthOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "UniversalMaterialType" = "Unlit"
      }
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      ColorMask 0
      GpuProgramID 383692
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // TEXCOORD                 0   xyz         1     NONE   float   xyz 
          // TEXCOORD                 1   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[73], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[70].xyzw
          mad r1.xyzw, cb0[69].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[71].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[72].xyzw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // TEXCOORD                 0   xyz         1     NONE   float       
          // TEXCOORD                 1   xyzw        2     NONE   float       
          // TEXCOORD                 2   xyzw        3     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_output o0.xyzw
          mov o0.xyzw, l(0,0,0,0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  FallBack "Hidden/Shader Graph/FallbackError"
}
