using System.Collections.Generic;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace ProjectArk.SpaceLife.Editor
{
    /// <summary>
    /// Read-only validator that inspects <c>DialogueUIPresenter</c> / <c>GiftUIPresenter</c>
    /// prefab instances in the currently open scene(s) and reports any property modification
    /// (override) that is not on the SpaceLife UI-prefab override whitelist.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Master Plan v1.1 Phase 2 (§6.3):</b> required Validator #2. Enforces the
    /// "UI Prefab zero-override" invariant declared in §4.1 by flagging any serialized
    /// field that drifts from the canonical <c>SpaceLifeUIPrefabBuilder</c> output.
    /// </para>
    /// <para>
    /// <b>Whitelist (allowed overrides):</b>
    /// </para>
    /// <list type="bullet">
    /// <item><see cref="Canvas.sortingOrder"/> — explicitly allowed in §4.1.</item>
    /// <item><c>m_Name</c> — renaming the scene instance is cosmetic and harmless.</item>
    /// </list>
    /// <para>
    /// <b>Forbidden (reports <see cref="Debug.LogError(object)"/>):</b> every other property
    /// modification — child hierarchy, CanvasGroup initial values, RectTransform layout,
    /// any serialized reference of the Presenter components, any numeric field.
    /// </para>
    /// <para>
    /// <b>Authority:</b> read-only. This tool must never mutate scene state, never touch
    /// the prefab asset, and never run on <c>OnValidate</c> / <c>Awake</c> / play-mode entry.
    /// Per Implement_rules.md §3.14, validators are Audit-mode only.
    /// </para>
    /// <para>
    /// <b>Scope:</b> scans every currently loaded scene via
    /// <see cref="SceneManager.GetSceneAt(int)"/>, which covers <c>SampleScene</c> and any
    /// additively loaded scenes.
    /// </para>
    /// </remarks>
    internal static class SpaceLifeUIOverrideAudit
    {
        private const string MenuPath = "ProjectArk/Space Life/Audit UI Prefab Overrides";

        /// <summary>
        /// Property paths that are allowed to diverge from the prefab asset.
        /// Every other modification produces a <see cref="Debug.LogError(object)"/>.
        /// </summary>
        private static readonly HashSet<string> AllowedPropertyPaths = new HashSet<string>
        {
            // §4.1: Canvas sorting order is the only numeric override explicitly allowed.
            "m_SortingOrder",
            // Renaming a scene instance is cosmetic; never affects rendered UI.
            "m_Name",
        };

        /// <summary>
        /// Target components whose root GameObject will be audited. Each target corresponds
        /// to a prefab generated by <c>SpaceLifeUIPrefabBuilder</c>.
        /// </summary>
        private static readonly System.Type[] AuditedPresenterTypes =
        {
            typeof(DialogueUIPresenter),
            typeof(GiftUIPresenter),
        };

        [MenuItem(MenuPath, priority = 12)]
        private static void Run()
        {
            var report = new StringBuilder();
            int totalInstances = 0;
            int totalViolations = 0;

            report.AppendLine("=== SpaceLifeUIOverrideAudit ===");
            report.AppendLine("Scope: all currently loaded scenes (excluding prefab staging).");
            report.AppendLine();

            int loadedSceneCount = SceneManager.sceneCount;
            if (loadedSceneCount == 0)
            {
                Debug.LogWarning("[SpaceLifeUIOverrideAudit] No scenes are currently loaded.");
                return;
            }

            for (int sceneIndex = 0; sceneIndex < loadedSceneCount; sceneIndex++)
            {
                Scene scene = SceneManager.GetSceneAt(sceneIndex);
                if (!scene.isLoaded)
                {
                    continue;
                }

                report.AppendLine($"[Scene] {scene.name} ({scene.path})");

                int sceneInstanceCount = 0;
                int sceneViolationCount = 0;

                foreach (System.Type presenterType in AuditedPresenterTypes)
                {
                    // Include inactive GameObjects; we still audit them because SpaceLife
                    // UI presenters are expected to stay active and rely on CanvasGroup
                    // for visibility (Implement_rules.md §12.6 R5). Sort order is not
                    // meaningful here, so we use the overload without FindObjectsSortMode.
                    Object[] presenters = Object.FindObjectsByType(
                        presenterType,
                        FindObjectsInactive.Include);

                    foreach (Object presenterObject in presenters)
                    {
                        var presenter = presenterObject as Component;
                        if (presenter == null)
                        {
                            continue;
                        }

                        // Only audit presenters that belong to the scene we are iterating.
                        if (presenter.gameObject.scene != scene)
                        {
                            continue;
                        }

                        int violations = AuditPresenterInstance(presenter, report);
                        sceneInstanceCount++;
                        sceneViolationCount += violations;
                    }
                }

                if (sceneInstanceCount == 0)
                {
                    report.AppendLine("  (no SpaceLife UI presenters found in this scene)");
                }

                report.AppendLine(
                    $"  -- Scene summary: {sceneInstanceCount} presenter instance(s), " +
                    $"{sceneViolationCount} violation(s).");
                report.AppendLine();

                totalInstances += sceneInstanceCount;
                totalViolations += sceneViolationCount;
            }

            report.AppendLine(
                $"=== Summary: {totalInstances} presenter instance(s) audited, " +
                $"{totalViolations} violation(s). ===");

            if (totalViolations > 0)
            {
                Debug.LogError(report.ToString());
            }
            else
            {
                Debug.Log(report.ToString());
            }
        }

        /// <summary>
        /// Audits a single presenter instance and its prefab root. Appends findings to the
        /// shared report and returns the number of forbidden modifications detected.
        /// </summary>
        /// <remarks>
        /// Uses <see cref="PrefabUtility.GetNearestPrefabInstanceRoot(Object)"/> so that
        /// nested prefabs (e.g. <c>DialogueUI</c> nested inside <c>SpaceLifeUIRoot</c>)
        /// are correctly resolved to their own prefab root before collecting modifications.
        /// </remarks>
        private static int AuditPresenterInstance(Component presenter, StringBuilder report)
        {
            GameObject presenterGameObject = presenter.gameObject;
            string scenePath = GetSceneHierarchyPath(presenterGameObject);

            // Accept both standalone prefab instances and nested prefab instances.
            if (!PrefabUtility.IsPartOfPrefabInstance(presenterGameObject))
            {
                report.AppendLine(
                    $"  [ERROR] {presenter.GetType().Name} at '{scenePath}' is NOT a prefab " +
                    "instance. SpaceLife UI presenters must originate from " +
                    "SpaceLifeUIPrefabBuilder-generated prefabs.");
                return 1;
            }

            GameObject prefabRoot = PrefabUtility.GetNearestPrefabInstanceRoot(presenterGameObject);
            if (prefabRoot == null)
            {
                report.AppendLine(
                    $"  [ERROR] Could not resolve prefab root for '{scenePath}'.");
                return 1;
            }

            Object prefabAsset = PrefabUtility.GetCorrespondingObjectFromSource(prefabRoot);
            string prefabAssetPath = prefabAsset != null
                ? AssetDatabase.GetAssetPath(prefabAsset)
                : "<unknown>";

            PropertyModification[] modifications =
                PrefabUtility.GetPropertyModifications(prefabRoot);

            if (modifications == null || modifications.Length == 0)
            {
                report.AppendLine(
                    $"  [OK] {presenter.GetType().Name} at '{scenePath}' " +
                    $"(prefab: {prefabAssetPath}) — no modifications.");
                return 0;
            }

            int violationCount = 0;
            int allowedCount = 0;
            var violationBuffer = new StringBuilder();

            foreach (PropertyModification mod in modifications)
            {
                if (mod == null || mod.target == null)
                {
                    continue;
                }

                // Unity records per-instance fileId bookkeeping in the modifications list.
                // Those appear as empty propertyPath entries; skip them.
                if (string.IsNullOrEmpty(mod.propertyPath))
                {
                    continue;
                }

                if (IsWhitelisted(mod.propertyPath))
                {
                    allowedCount++;
                    continue;
                }

                violationCount++;
                string targetTypeName = mod.target != null
                    ? mod.target.GetType().Name
                    : "<null>";
                string currentValue = string.IsNullOrEmpty(mod.value)
                    ? "<empty>"
                    : mod.value;
                violationBuffer.AppendLine(
                    $"    - '{mod.propertyPath}' on <{targetTypeName}> = '{currentValue}'");
            }

            if (violationCount == 0)
            {
                report.AppendLine(
                    $"  [OK] {presenter.GetType().Name} at '{scenePath}' " +
                    $"(prefab: {prefabAssetPath}) — {allowedCount} whitelisted modification(s), " +
                    "0 violation(s).");
                return 0;
            }

            report.AppendLine(
                $"  [VIOLATION] {presenter.GetType().Name} at '{scenePath}' " +
                $"(prefab: {prefabAssetPath}) — {violationCount} forbidden override(s), " +
                $"{allowedCount} whitelisted:");
            report.Append(violationBuffer);
            return violationCount;
        }

        /// <summary>
        /// <c>true</c> when the given serialized property path is allowed to override the
        /// prefab asset per Master Plan §4.1.
        /// </summary>
        private static bool IsWhitelisted(string propertyPath)
        {
            return AllowedPropertyPaths.Contains(propertyPath);
        }

        /// <summary>
        /// Builds a <c>/</c>-separated hierarchy path for the given GameObject, used in
        /// human-readable audit output.
        /// </summary>
        private static string GetSceneHierarchyPath(GameObject gameObject)
        {
            if (gameObject == null)
            {
                return "<null>";
            }

            var builder = new StringBuilder(gameObject.name);
            Transform current = gameObject.transform.parent;
            while (current != null)
            {
                builder.Insert(0, current.name + "/");
                current = current.parent;
            }

            return builder.ToString();
        }
    }
}
