using System;
using System.Collections.Generic;
using System.Threading;
using Cysharp.Threading.Tasks;
using ProjectArk.Core;
using ProjectArk.SpaceLife.Dialogue;
using UnityEngine;
using UnityEngine.UI;

namespace ProjectArk.SpaceLife
{
    /// <summary>
    /// Presentation-layer implementation of <see cref="IDialoguePresenter"/>.
    /// Renders <see cref="DialogueNodeViewModel"/> produced by <see cref="DialogueRunner"/>
    /// and publishes <see cref="OnChoiceSelected"/> when the player clicks a choice.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Master Plan v1.1 Phase 2 (§6.2.1):</b> replaces the legacy <c>DialogueUI</c> class
    /// (deleted). Differences from legacy <c>DialogueUI</c>:
    /// </para>
    /// <list type="bullet">
    /// <item>Implements <see cref="IDialoguePresenter"/>; no longer consumed by concrete type.</item>
    /// <item>No direct relationship / GiftUI coupling; choices only surface <c>choiceId</c>.</item>
    /// <item>No legacy <c>DialogueLine</c> / index-based navigation (<c>NPCDataSO.DialogueNodes</c> path).</item>
    /// <item>Visibility is controlled via <see cref="CanvasGroup"/> (alpha + interactable + blocksRaycasts).
    ///       Never <c>SetActive(false)</c> on the panel — see Implement_rules.md §12.6 R5.</item>
    /// </list>
    /// <para>
    /// <b>Ownership:</b> registers itself into <see cref="ServiceLocator"/> as both the concrete
    /// <see cref="DialogueUIPresenter"/> type (for Phase 2 scene wiring) and as
    /// <see cref="IDialoguePresenter"/> (for Phase 3 <c>SpaceLifeDialogueCoordinator</c> resolution).
    /// </para>
    /// <para>
    /// <b>Prefab authority:</b> the full prefab hierarchy (Canvas / Panel / Text / Button / CanvasGroup)
    /// is generated by <c>SpaceLifeUIPrefabBuilder</c>. Scene override is forbidden except for the
    /// items listed in Master Plan v1.1 §4.1.
    /// </para>
    /// </remarks>
    public class DialogueUIPresenter : MonoBehaviour, IDialoguePresenter
    {
        [Header("UI Root")]
        [SerializeField] private GameObject _dialoguePanel;
        [SerializeField] private CanvasGroup _dialogueCanvasGroup;

        [Header("UI Elements")]
        [SerializeField] private Image _avatarImage;
        [SerializeField] private Text _speakerNameText;
        [SerializeField] private Text _dialogueText;
        [SerializeField] private Transform _optionsContainer;
        [SerializeField] private GameObject _optionButtonPrefab;
        [SerializeField] private Button _closeButton;

        [Header("Settings")]
        [SerializeField] private float _typewriterSpeed = 0.05f;

        [Header("Option Layout")]
        [SerializeField] private float _choiceButtonHeight = 44f;
        [SerializeField] private float _choiceButtonHorizontalPadding = 16f;
        [SerializeField] private float _choiceButtonVerticalPadding = 6f;
        [SerializeField] private float _dialogueToOptionsGap = 8f;

        private DialogueNodeViewModel _currentNode;
        private CancellationTokenSource _typewriterCts;
        private RectTransform _dialogueTextRect;
        private RectTransform _optionsRect;
        private VerticalLayoutGroup _optionsLayoutGroup;
        private float _defaultDialogueTextBottomInset;
        private float _defaultOptionsTopInset;
        private float _defaultOptionsBottomInset;
        private bool _layoutDefaultsCached;

        /// <inheritdoc />
        public event Action<string> OnChoiceSelected;

        /// <summary>
        /// <c>true</c> when the dialogue panel is currently visible (alpha &gt; 0).
        /// </summary>
        public bool IsVisible => _dialogueCanvasGroup != null && _dialogueCanvasGroup.alpha > 0.001f;

        /// <summary>
        /// The node currently displayed, or <c>null</c> when hidden.
        /// </summary>
        public DialogueNodeViewModel CurrentNode => _currentNode;

        private void Awake()
        {
            ResolveCanvasGroup();
            ApplyVisibility(false);

            if (_closeButton != null)
            {
                _closeButton.onClick.AddListener(RequestClose);
            }

            ServiceLocator.Register(this);
            ServiceLocator.Register<IDialoguePresenter>(this);
        }

        /// <inheritdoc />
        public void ShowNode(DialogueNodeViewModel viewModel)
        {
            if (viewModel == null)
            {
                Debug.LogError("[DialogueUIPresenter] ShowNode received a null view model.", this);
                return;
            }

            _currentNode = viewModel;
            ApplyVisibility(true);
            RenderNode(viewModel);
        }

        /// <inheritdoc />
        public void HideDialogue()
        {
            CancelTypewriter();
            ClearOptions();
            SetCloseButtonVisible(true);
            ApplyVisibility(false);

            _currentNode = null;

            if (_speakerNameText != null)
            {
                _speakerNameText.text = string.Empty;
            }

            if (_dialogueText != null)
            {
                _dialogueText.text = string.Empty;
            }

            if (_avatarImage != null)
            {
                _avatarImage.sprite = null;
                _avatarImage.enabled = false;
            }
        }

        private void RenderNode(DialogueNodeViewModel node)
        {
            CacheLayoutDefaults();
            NormalizeOptionsContainer();

            if (_speakerNameText != null)
            {
                _speakerNameText.text = string.IsNullOrWhiteSpace(node.SpeakerName)
                    ? string.Empty
                    : node.SpeakerName;
            }

            if (_dialogueText != null)
            {
                CancelTypewriter();
                _typewriterCts = new CancellationTokenSource();
                TypeTextAsync(node.Text ?? string.Empty, _typewriterCts.Token).Forget();
            }

            ClearOptions();

            IReadOnlyList<DialogueNodeViewModel.ChoiceViewModel> choices = node.Choices;
            bool hasExplicitChoices = choices != null && choices.Count > 0;
            bool isSingleAcknowledgementChoice = hasExplicitChoices && choices.Count == 1;
            SetCloseButtonVisible(!isSingleAcknowledgementChoice);
            if (hasExplicitChoices)
            {
                for (int i = 0; i < choices.Count; i++)
                {
                    CreateChoiceButton(choices[i]);
                }

                ApplyOptionAreaLayout(choices.Count);
                return;
            }

            // No explicit choices: surface a synthetic "Continue" / "Close" button that
            // still goes through the same OnChoiceSelected contract with a reserved id.
            // The Coordinator is expected to map these to Runner.Continue() / HideDialogue().
            if (node.NodeType == DialogueNodeType.Line)
            {
                CreateUtilityButton("继续", DialoguePresenterReservedChoices.Continue);
            }
            else
            {
                CreateUtilityButton("关闭", DialoguePresenterReservedChoices.Close);
            }

            ApplyOptionAreaLayout(1);
        }

        private void RequestClose()
        {
            // The close button short-circuits to the reserved "__close__" choice id so the
            // Coordinator can decide whether to Hide or route a service exit.
            OnChoiceSelected?.Invoke(DialoguePresenterReservedChoices.Close);
        }

        private async UniTaskVoid TypeTextAsync(string text, CancellationToken ct)
        {
            if (_dialogueText != null)
            {
                _dialogueText.text = string.Empty;
            }

            try
            {
                foreach (char c in text)
                {
                    if (ct.IsCancellationRequested)
                    {
                        return;
                    }

                    if (_dialogueText != null)
                    {
                        _dialogueText.text += c;
                    }

                    await UniTask.Delay(TimeSpan.FromSeconds(_typewriterSpeed), cancellationToken: ct);
                }
            }
            catch (OperationCanceledException)
            {
            }
        }

        private void CancelTypewriter()
        {
            if (_typewriterCts != null)
            {
                _typewriterCts.Cancel();
                _typewriterCts.Dispose();
                _typewriterCts = null;
            }
        }

        private void ClearOptions()
        {
            if (_optionsContainer == null)
            {
                return;
            }

            for (int i = _optionsContainer.childCount - 1; i >= 0; i--)
            {
                Destroy(_optionsContainer.GetChild(i).gameObject);
            }
        }

        private void CreateChoiceButton(DialogueNodeViewModel.ChoiceViewModel choice)
        {
            if (choice == null)
            {
                return;
            }

            CreateUtilityButton(choice.Text, choice.ChoiceId);
        }

        private void CreateUtilityButton(string buttonText, string choiceId)
        {
            if (_optionButtonPrefab == null || _optionsContainer == null)
            {
                Debug.LogError("[DialogueUIPresenter] Option button prefab or container is missing.", this);
                return;
            }

            GameObject buttonObject = Instantiate(_optionButtonPrefab, _optionsContainer);
            Button button = buttonObject.GetComponent<Button>();
            Text buttonLabel = buttonObject.GetComponentInChildren<Text>();

            if (buttonLabel != null)
            {
                buttonLabel.text = buttonText;
            }

            ConfigureOptionButton(buttonObject, buttonLabel);

            if (button == null)
            {
                Debug.LogError("[DialogueUIPresenter] Option button prefab is missing a Button component.", this);
                return;
            }

            // Capture the choice id in a local so the lambda keeps a stable reference.
            string capturedId = choiceId;
            button.onClick.AddListener(() => OnChoiceSelected?.Invoke(capturedId));
        }

        private void ConfigureOptionButton(GameObject buttonObject, Text buttonLabel)
        {
            if (buttonObject == null)
            {
                return;
            }

            RectTransform buttonRect = buttonObject.GetComponent<RectTransform>();
            if (buttonRect != null)
            {
                buttonRect.anchorMin = new Vector2(0f, 0f);
                buttonRect.anchorMax = new Vector2(1f, 0f);
                buttonRect.pivot = new Vector2(0.5f, 0f);
                buttonRect.sizeDelta = new Vector2(0f, _choiceButtonHeight);
            }

            LayoutElement layoutElement = buttonObject.GetComponent<LayoutElement>();
            if (layoutElement == null)
            {
                layoutElement = buttonObject.AddComponent<LayoutElement>();
            }

            layoutElement.minHeight = _choiceButtonHeight;
            layoutElement.preferredHeight = _choiceButtonHeight;
            layoutElement.flexibleHeight = 0f;

            if (buttonLabel == null)
            {
                return;
            }

            buttonLabel.alignment = TextAnchor.MiddleLeft;
            buttonLabel.horizontalOverflow = HorizontalWrapMode.Wrap;
            buttonLabel.verticalOverflow = VerticalWrapMode.Overflow;
            buttonLabel.resizeTextForBestFit = false;
            buttonLabel.raycastTarget = false;

            RectTransform labelRect = buttonLabel.transform as RectTransform;
            if (labelRect == null)
            {
                return;
            }

            labelRect.anchorMin = Vector2.zero;
            labelRect.anchorMax = Vector2.one;
            labelRect.pivot = new Vector2(0.5f, 0.5f);
            labelRect.offsetMin = new Vector2(_choiceButtonHorizontalPadding, _choiceButtonVerticalPadding);
            labelRect.offsetMax = new Vector2(-_choiceButtonHorizontalPadding, -_choiceButtonVerticalPadding);
        }

        private void NormalizeOptionsContainer()
        {
            if (_optionsLayoutGroup == null && _optionsContainer != null)
            {
                _optionsLayoutGroup = _optionsContainer.GetComponent<VerticalLayoutGroup>();
            }

            if (_optionsLayoutGroup == null)
            {
                return;
            }

            _optionsLayoutGroup.childAlignment = TextAnchor.UpperLeft;
            _optionsLayoutGroup.childControlWidth = true;
            _optionsLayoutGroup.childControlHeight = true;
            _optionsLayoutGroup.childForceExpandWidth = true;
            _optionsLayoutGroup.childForceExpandHeight = false;
        }

        private void ApplyOptionAreaLayout(int optionCount)
        {
            CacheLayoutDefaults();

            if (_optionsRect == null || _dialogueTextRect == null)
            {
                return;
            }

            float spacing = _optionsLayoutGroup != null ? _optionsLayoutGroup.spacing : 0f;
            float requiredHeight = optionCount > 0
                ? (optionCount * _choiceButtonHeight) + (Mathf.Max(0, optionCount - 1) * spacing)
                : _defaultOptionsTopInset - _defaultOptionsBottomInset;

            float targetOptionsTopInset = Mathf.Max(_defaultOptionsTopInset, _defaultOptionsBottomInset + requiredHeight);
            _optionsRect.offsetMax = new Vector2(_optionsRect.offsetMax.x, targetOptionsTopInset);

            float targetDialogueBottomInset = Mathf.Max(_defaultDialogueTextBottomInset, targetOptionsTopInset + _dialogueToOptionsGap);
            _dialogueTextRect.offsetMin = new Vector2(_dialogueTextRect.offsetMin.x, targetDialogueBottomInset);

            LayoutRebuilder.ForceRebuildLayoutImmediate(_optionsRect);
        }

        private void RestoreOptionAreaLayout()
        {
            CacheLayoutDefaults();

            if (_optionsRect != null)
            {
                _optionsRect.offsetMin = new Vector2(_optionsRect.offsetMin.x, _defaultOptionsBottomInset);
                _optionsRect.offsetMax = new Vector2(_optionsRect.offsetMax.x, _defaultOptionsTopInset);
            }

            if (_dialogueTextRect != null)
            {
                _dialogueTextRect.offsetMin = new Vector2(_dialogueTextRect.offsetMin.x, _defaultDialogueTextBottomInset);
            }
        }

        private void CacheLayoutDefaults()
        {
            if (_layoutDefaultsCached)
            {
                return;
            }

            _dialogueTextRect = _dialogueText != null ? _dialogueText.transform as RectTransform : null;
            _optionsRect = _optionsContainer as RectTransform;
            _optionsLayoutGroup = _optionsContainer != null ? _optionsContainer.GetComponent<VerticalLayoutGroup>() : null;

            if (_dialogueTextRect == null || _optionsRect == null)
            {
                return;
            }

            _defaultDialogueTextBottomInset = _dialogueTextRect.offsetMin.y;
            _defaultOptionsBottomInset = _optionsRect.offsetMin.y;
            _defaultOptionsTopInset = _optionsRect.offsetMax.y;
            _layoutDefaultsCached = true;
        }

        private void SetCloseButtonVisible(bool isVisible)
        {
            if (_closeButton == null)
            {
                return;
            }

            GameObject closeButtonObject = _closeButton.gameObject;
            if (closeButtonObject.activeSelf == isVisible)
            {
                return;
            }

            closeButtonObject.SetActive(isVisible);
        }

        /// <summary>
        /// Assigns the speaker avatar sprite. Not part of <see cref="IDialoguePresenter"/>
        /// because avatars are a presentation-only concern; the Coordinator can access
        /// this via the concrete type when needed.
        /// </summary>
        public void SetSpeakerAvatar(Sprite avatar)
        {
            if (_avatarImage == null)
            {
                return;
            }

            _avatarImage.sprite = avatar;
            _avatarImage.enabled = avatar != null;
        }

        private void ApplyVisibility(bool isVisible)
        {
            if (_dialogueCanvasGroup == null)
            {
                return;
            }

            _dialogueCanvasGroup.alpha = isVisible ? 1f : 0f;
            _dialogueCanvasGroup.interactable = isVisible;
            _dialogueCanvasGroup.blocksRaycasts = isVisible;
        }

        private void ResolveCanvasGroup()
        {
            if (_dialogueCanvasGroup != null)
            {
                return;
            }

            if (_dialoguePanel != null)
            {
                _dialogueCanvasGroup = _dialoguePanel.GetComponent<CanvasGroup>();
            }

            if (_dialogueCanvasGroup == null)
            {
                _dialogueCanvasGroup = GetComponent<CanvasGroup>();
            }

            if (_dialogueCanvasGroup == null)
            {
                Debug.LogError(
                    "[DialogueUIPresenter] Missing CanvasGroup. Assign one on the root panel " +
                    "(SpaceLifeUIPrefabBuilder generates it automatically).",
                    this);
            }
        }

        private void OnDestroy()
        {
            CancelTypewriter();
            OnChoiceSelected = null;

            if (_closeButton != null)
            {
                _closeButton.onClick.RemoveListener(RequestClose);
            }

            ServiceLocator.Unregister(this);
            ServiceLocator.Unregister<IDialoguePresenter>(this);
        }
    }

    /// <summary>
    /// Reserved choice ids surfaced by <see cref="DialogueUIPresenter"/> when a node has no
    /// explicit choices (synthetic "Continue" / "Close" buttons). The Coordinator is responsible
    /// for mapping these to <c>DialogueRunner.Continue()</c> or <c>HideDialogue()</c> respectively.
    /// </summary>
    /// <remarks>
    /// Kept separate from real <c>ChoiceViewModel.ChoiceId</c> values by prefixing with
    /// double underscore. Runner-produced ids use slugs from <c>DialogueChoiceData</c>.
    /// </remarks>
    public static class DialoguePresenterReservedChoices
    {
        public const string Continue = "__continue__";
        public const string Close = "__close__";
    }
}
