using System;
using System.Collections.Generic;
using System.Threading;
using Cysharp.Threading.Tasks;
using ProjectArk.Core;
using ProjectArk.SpaceLife.Dialogue;
using UnityEngine;
using UnityEngine.UI;

namespace ProjectArk.SpaceLife
{
    /// <summary>
    /// Presentation-layer implementation of <see cref="IDialoguePresenter"/>.
    /// Renders <see cref="DialogueNodeViewModel"/> produced by <see cref="DialogueRunner"/>
    /// and publishes <see cref="OnChoiceSelected"/> when the player clicks a choice.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Master Plan v1.1 Phase 2 (§6.2.1):</b> replaces the legacy <c>DialogueUI</c> class
    /// (deleted). Differences from legacy <c>DialogueUI</c>:
    /// </para>
    /// <list type="bullet">
    /// <item>Implements <see cref="IDialoguePresenter"/>; no longer consumed by concrete type.</item>
    /// <item>No direct relationship / GiftUI coupling; choices only surface <c>choiceId</c>.</item>
    /// <item>No legacy <c>DialogueLine</c> / index-based navigation (<c>NPCDataSO.DialogueNodes</c> path).</item>
    /// <item>Visibility is controlled via <see cref="CanvasGroup"/> (alpha + interactable + blocksRaycasts).
    ///       Never <c>SetActive(false)</c> on the panel — see Implement_rules.md §12.6 R5.</item>
    /// </list>
    /// <para>
    /// <b>Ownership:</b> registers itself into <see cref="ServiceLocator"/> as both the concrete
    /// <see cref="DialogueUIPresenter"/> type (for Phase 2 scene wiring) and as
    /// <see cref="IDialoguePresenter"/> (for Phase 3 <c>SpaceLifeDialogueCoordinator</c> resolution).
    /// </para>
    /// <para>
    /// <b>Prefab authority:</b> the full prefab hierarchy (Canvas / Panel / Text / Button / CanvasGroup)
    /// is generated by <c>SpaceLifeUIPrefabBuilder</c>. Scene override is forbidden except for the
    /// items listed in Master Plan v1.1 §4.1.
    /// </para>
    /// </remarks>
    public class DialogueUIPresenter : MonoBehaviour, IDialoguePresenter
    {
        [Header("UI Root")]
        [SerializeField] private GameObject _dialoguePanel;
        [SerializeField] private CanvasGroup _dialogueCanvasGroup;

        [Header("UI Elements")]
        [SerializeField] private Image _avatarImage;
        [SerializeField] private Text _speakerNameText;
        [SerializeField] private Text _dialogueText;
        [SerializeField] private Transform _optionsContainer;
        [SerializeField] private GameObject _optionButtonPrefab;
        [SerializeField] private Button _closeButton;

        [Header("Settings")]
        [SerializeField] private float _typewriterSpeed = 0.05f;

        private DialogueNodeViewModel _currentNode;
        private CancellationTokenSource _typewriterCts;

        /// <inheritdoc />
        public event Action<string> OnChoiceSelected;

        /// <summary>
        /// <c>true</c> when the dialogue panel is currently visible (alpha &gt; 0).
        /// </summary>
        public bool IsVisible => _dialogueCanvasGroup != null && _dialogueCanvasGroup.alpha > 0.001f;

        /// <summary>
        /// The node currently displayed, or <c>null</c> when hidden.
        /// </summary>
        public DialogueNodeViewModel CurrentNode => _currentNode;

        private void Awake()
        {
            ResolveCanvasGroup();
            ApplyVisibility(false);

            if (_closeButton != null)
            {
                _closeButton.onClick.AddListener(RequestClose);
            }

            ServiceLocator.Register(this);
            ServiceLocator.Register<IDialoguePresenter>(this);
        }

        /// <inheritdoc />
        public void ShowNode(DialogueNodeViewModel viewModel)
        {
            if (viewModel == null)
            {
                Debug.LogError("[DialogueUIPresenter] ShowNode received a null view model.", this);
                return;
            }

            _currentNode = viewModel;
            ApplyVisibility(true);
            RenderNode(viewModel);
        }

        /// <inheritdoc />
        public void HideDialogue()
        {
            CancelTypewriter();
            ClearOptions();
            ApplyVisibility(false);

            _currentNode = null;

            if (_speakerNameText != null)
            {
                _speakerNameText.text = string.Empty;
            }

            if (_dialogueText != null)
            {
                _dialogueText.text = string.Empty;
            }

            if (_avatarImage != null)
            {
                _avatarImage.sprite = null;
                _avatarImage.enabled = false;
            }
        }

        private void RenderNode(DialogueNodeViewModel node)
        {
            if (_speakerNameText != null)
            {
                _speakerNameText.text = string.IsNullOrWhiteSpace(node.SpeakerName)
                    ? string.Empty
                    : node.SpeakerName;
            }

            if (_dialogueText != null)
            {
                CancelTypewriter();
                _typewriterCts = new CancellationTokenSource();
                TypeTextAsync(node.Text ?? string.Empty, _typewriterCts.Token).Forget();
            }

            ClearOptions();

            IReadOnlyList<DialogueNodeViewModel.ChoiceViewModel> choices = node.Choices;
            if (choices != null && choices.Count > 0)
            {
                for (int i = 0; i < choices.Count; i++)
                {
                    CreateChoiceButton(choices[i]);
                }

                return;
            }

            // No explicit choices: surface a synthetic "Continue" / "Close" button that
            // still goes through the same OnChoiceSelected contract with a reserved id.
            // The Coordinator is expected to map these to Runner.Continue() / HideDialogue().
            if (node.NodeType == DialogueNodeType.Line)
            {
                CreateUtilityButton("继续", DialoguePresenterReservedChoices.Continue);
            }
            else
            {
                CreateUtilityButton("关闭", DialoguePresenterReservedChoices.Close);
            }
        }

        private void RequestClose()
        {
            // The close button short-circuits to the reserved "__close__" choice id so the
            // Coordinator can decide whether to Hide or route a service exit.
            OnChoiceSelected?.Invoke(DialoguePresenterReservedChoices.Close);
        }

        private async UniTaskVoid TypeTextAsync(string text, CancellationToken ct)
        {
            if (_dialogueText != null)
            {
                _dialogueText.text = string.Empty;
            }

            try
            {
                foreach (char c in text)
                {
                    if (ct.IsCancellationRequested)
                    {
                        return;
                    }

                    if (_dialogueText != null)
                    {
                        _dialogueText.text += c;
                    }

                    await UniTask.Delay(TimeSpan.FromSeconds(_typewriterSpeed), cancellationToken: ct);
                }
            }
            catch (OperationCanceledException)
            {
            }
        }

        private void CancelTypewriter()
        {
            if (_typewriterCts != null)
            {
                _typewriterCts.Cancel();
                _typewriterCts.Dispose();
                _typewriterCts = null;
            }
        }

        private void ClearOptions()
        {
            if (_optionsContainer == null)
            {
                return;
            }

            for (int i = _optionsContainer.childCount - 1; i >= 0; i--)
            {
                Destroy(_optionsContainer.GetChild(i).gameObject);
            }
        }

        private void CreateChoiceButton(DialogueNodeViewModel.ChoiceViewModel choice)
        {
            if (choice == null)
            {
                return;
            }

            CreateUtilityButton(choice.Text, choice.ChoiceId);
        }

        private void CreateUtilityButton(string buttonText, string choiceId)
        {
            if (_optionButtonPrefab == null || _optionsContainer == null)
            {
                Debug.LogError("[DialogueUIPresenter] Option button prefab or container is missing.", this);
                return;
            }

            GameObject buttonObject = Instantiate(_optionButtonPrefab, _optionsContainer);
            Button button = buttonObject.GetComponent<Button>();
            Text buttonLabel = buttonObject.GetComponentInChildren<Text>();

            if (buttonLabel != null)
            {
                buttonLabel.text = buttonText;
            }

            if (button == null)
            {
                Debug.LogError("[DialogueUIPresenter] Option button prefab is missing a Button component.", this);
                return;
            }

            // Capture the choice id in a local so the lambda keeps a stable reference.
            string capturedId = choiceId;
            button.onClick.AddListener(() => OnChoiceSelected?.Invoke(capturedId));
        }

        /// <summary>
        /// Assigns the speaker avatar sprite. Not part of <see cref="IDialoguePresenter"/>
        /// because avatars are a presentation-only concern; the Coordinator can access
        /// this via the concrete type when needed.
        /// </summary>
        public void SetSpeakerAvatar(Sprite avatar)
        {
            if (_avatarImage == null)
            {
                return;
            }

            _avatarImage.sprite = avatar;
            _avatarImage.enabled = avatar != null;
        }

        private void ApplyVisibility(bool isVisible)
        {
            if (_dialogueCanvasGroup == null)
            {
                return;
            }

            _dialogueCanvasGroup.alpha = isVisible ? 1f : 0f;
            _dialogueCanvasGroup.interactable = isVisible;
            _dialogueCanvasGroup.blocksRaycasts = isVisible;
        }

        private void ResolveCanvasGroup()
        {
            if (_dialogueCanvasGroup != null)
            {
                return;
            }

            if (_dialoguePanel != null)
            {
                _dialogueCanvasGroup = _dialoguePanel.GetComponent<CanvasGroup>();
            }

            if (_dialogueCanvasGroup == null)
            {
                _dialogueCanvasGroup = GetComponent<CanvasGroup>();
            }

            if (_dialogueCanvasGroup == null)
            {
                Debug.LogError(
                    "[DialogueUIPresenter] Missing CanvasGroup. Assign one on the root panel " +
                    "(SpaceLifeUIPrefabBuilder generates it automatically).",
                    this);
            }
        }

        private void OnDestroy()
        {
            CancelTypewriter();
            OnChoiceSelected = null;

            if (_closeButton != null)
            {
                _closeButton.onClick.RemoveListener(RequestClose);
            }

            ServiceLocator.Unregister(this);
            ServiceLocator.Unregister<IDialoguePresenter>(this);
        }
    }

    /// <summary>
    /// Reserved choice ids surfaced by <see cref="DialogueUIPresenter"/> when a node has no
    /// explicit choices (synthetic "Continue" / "Close" buttons). The Coordinator is responsible
    /// for mapping these to <c>DialogueRunner.Continue()</c> or <c>HideDialogue()</c> respectively.
    /// </summary>
    /// <remarks>
    /// Kept separate from real <c>ChoiceViewModel.ChoiceId</c> values by prefixing with
    /// double underscore. Runner-produced ids use slugs from <c>DialogueChoiceData</c>.
    /// </remarks>
    public static class DialoguePresenterReservedChoices
    {
        public const string Continue = "__continue__";
        public const string Close = "__close__";
    }
}
