Shader "Shader Graphs/Flashable"
{
  Properties
  {
    [NoScaleOffset] _MainTex ("MainTex", 2D) = "white" {}
    _FlashIntensity ("Flash Intensity", Range(0, 1)) = 1
    unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" {}
    unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" {}
    unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" {}
  }
  SubShader
  {
    Tags
    { 
      "QUEUE" = "Transparent"
      "RenderPipeline" = "UniversalPipeline"
      "RenderType" = "Transparent"
      "ShaderGraphShader" = "true"
      "ShaderGraphTargetId" = ""
      "UniversalMaterialType" = "Unlit"
    }
    Pass // ind: 1, name: Sprite Unlit
    {
      Name "Sprite Unlit"
      Tags
      { 
        "LIGHTMODE" = "Universal2D"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = ""
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Cull Off
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      GpuProgramID 13115
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2016
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Vector value_type=float4 name=_RendererColor offset=2000 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[126], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[76].xyzw
          mov o2.xyzw, v3.xyzw
          mul o3.xyzw, v4.xyzw, cb0[125].xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2016
          //    cbIndex=0 type=Vector value_type=float2 name=_GlobalMipBias offset=304 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerMaterial type=ConstantBuffer size=32
          //    cbIndex=1 type=Vector value_type=float name=_FlashIntensity offset=16 arraySize=0
          //
          // Uniform=1 type=Texture value_type=Texture2D name=_MainTex index=0 samplerIndex=0 multiSampled=0
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float       
          // INTERP                   1   xyzw        2     NONE   float   xy  
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_constantbuffer CB0[20], immediateIndexed
          dcl_constantbuffer CB1[2], immediateIndexed
          dcl_sampler s0, mode_default
          dcl_resource_texture2d (float,float,float,float) t0
          dcl_input_ps linear v2.xy
          dcl_input_ps linear v3.xyzw
          dcl_output o0.xyzw
          dcl_temps 2
          sample_b r0.xyzw, v2.xyxx, t0.xyzw, s0, cb0[19].x
          eq r1.x, r0.w, l(0.000000)
          discard_nz r1.x
          mad r1.x, cb1[1].x, l(9.000000), l(1.000000)
          mul r0.xyz, r0.xyzx, r1.xxxx
          mul o0.xyzw, r0.xyzw, v3.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 2, name: Sprite Unlit
    {
      Name "Sprite Unlit"
      Tags
      { 
        "LIGHTMODE" = "UniversalForward"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = ""
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Cull Off
      Blend SrcAlpha OneMinusSrcAlpha, One OneMinusSrcAlpha
      GpuProgramID 233228
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2016
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Vector value_type=float4 name=_RendererColor offset=2000 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float       
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[126], immediateIndexed
          dcl_constantbuffer CB1[4], immediateIndexed
          dcl_input v0.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          mov o1.xyz, r0.xyzx
          add o0.xyzw, r1.xyzw, cb0[76].xyzw
          mov o2.xyzw, v3.xyzw
          mul o3.xyzw, v4.xyzw, cb0[125].xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2016
          //    cbIndex=0 type=Vector value_type=float2 name=_GlobalMipBias offset=304 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerMaterial type=ConstantBuffer size=32
          //    cbIndex=1 type=Vector value_type=float name=_FlashIntensity offset=16 arraySize=0
          //
          // Uniform=1 type=Texture value_type=Texture2D name=_MainTex index=0 samplerIndex=0 multiSampled=0
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float       
          // INTERP                   1   xyzw        2     NONE   float   xy  
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_constantbuffer CB0[20], immediateIndexed
          dcl_constantbuffer CB1[2], immediateIndexed
          dcl_sampler s0, mode_default
          dcl_resource_texture2d (float,float,float,float) t0
          dcl_input_ps linear v2.xy
          dcl_input_ps linear v3.xyzw
          dcl_output o0.xyzw
          dcl_temps 2
          sample_b r0.xyzw, v2.xyxx, t0.xyzw, s0, cb0[19].x
          eq r1.x, r0.w, l(0.000000)
          discard_nz r1.x
          mad r1.x, cb1[1].x, l(9.000000), l(1.000000)
          mul r0.xyz, r0.xyzx, r1.xxxx
          mul o0.xyzw, r0.xyzw, v3.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  FallBack "Hidden/Shader Graph/FallbackError"
}
