Shader "Shader Graphs/LightSimuShader"
{
  Properties
  {
    [NoScaleOffset] _MainTex ("Texture2D", 2D) = "white" {}
    [HideInInspector] _QueueOffset ("_QueueOffset", float) = 0
    [HideInInspector] _QueueControl ("_QueueControl", float) = -1
    unity_Lightmaps ("unity_Lightmaps", 2DArray) = "" {}
    unity_LightmapsInd ("unity_LightmapsInd", 2DArray) = "" {}
    unity_ShadowMasks ("unity_ShadowMasks", 2DArray) = "" {}
  }
  SubShader
  {
    Tags
    { 
      "QUEUE" = "Transparent"
      "RenderPipeline" = "UniversalPipeline"
      "RenderType" = "Transparent"
      "ShaderGraphShader" = "true"
      "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
      "UniversalMaterialType" = "Unlit"
    }
    Pass // ind: 1, name: Universal Forward
    {
      Name "Universal Forward"
      Tags
      { 
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Blend SrcAlpha One, One One
      GpuProgramID 56951
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixV offset=976 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Vector value_type=float3 name=_WorldSpaceCameraPos offset=256 arraySize=0
          //    cbIndex=0 type=Vector value_type=float4 name=unity_OrthoParams offset=336 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyz         2     NONE   float   xyz 
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          // INTERP                   3   xyzw        4     NONE   float   xyzw
          // INTERP                   4   xyz         5     NONE   float   xyz 
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[77], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyz
          dcl_output o3.xyzw
          dcl_output o4.xyzw
          dcl_output o5.xyz
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r1.xyzw, cb0[76].xyzw
          mov o1.xyz, r0.xyzx
          add r0.xyz, -r0.xyzx, cb0[16].xyzx
          dp3 r1.x, v1.xyzx, cb1[4].xyzx
          dp3 r1.y, v1.xyzx, cb1[5].xyzx
          dp3 r1.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r1.xyzx, r1.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o2.xyz, r0.wwww, r1.xyzx
          mov o3.xyzw, v3.xyzw
          mov o4.xyzw, v4.xyzw
          eq r0.w, cb0[21].w, l(0.000000)
          movc o5.x, r0.w, r0.x, cb0[61].z
          movc o5.y, r0.w, r0.y, cb0[62].z
          movc o5.z, r0.w, r0.z, cb0[63].z
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Vector value_type=float2 name=_GlobalMipBias offset=304 arraySize=0
          //
          // Uniform=1 type=Texture value_type=Texture2D name=_MainTex index=0 samplerIndex=0 multiSampled=0
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float       
          // INTERP                   1   xyz         2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float   xy  
          // INTERP                   3   xyzw        4     NONE   float   xyzw
          // INTERP                   4   xyz         5     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[20], immediateIndexed
          dcl_sampler s0, mode_default
          dcl_resource_texture2d (float,float,float,float) t0
          dcl_input_ps linear v3.xy
          dcl_input_ps linear v4.xyzw
          dcl_output o0.xyzw
          dcl_temps 4
          sample_b_indexable(texture2d)(float,float,float,float) r0.xyzw, v3.xyxx, t0.xyzw, s0, cb0[19].x
          add r1.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
          mul r1.xyz, r1.xyzx, r1.xyzx
          mad r1.xyz, -r1.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
          ge r2.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), r0.xyzx
          movc r3.xyz, r2.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)
          and r2.xyz, r2.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
          mul r1.xyz, r1.xyzx, r3.xyzx
          mul r0.xyz, r0.xyzx, r0.xyzx
          add r0.xyz, r0.xyzx, r0.xyzx
          mad r0.xyz, r0.xyzx, r2.xyzx, r1.xyzx
          mul o0.xyzw, r0.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 2, name: DepthNormalsOnly
    {
      Name "DepthNormalsOnly"
      Tags
      { 
        "LIGHTMODE" = "DepthNormalsOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      GpuProgramID 84695
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // TEXCOORD                 1   xyzw        4     NONE   float       
          // COLOR                    0   xyzw        5     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          // INTERP                   3   xyzw        4     NONE   float   xyzw
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[77], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v2.xyzw
          dcl_input v3.xyzw
          dcl_input v5.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_output o4.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r0.xyzw, cb0[76].xyzw
          dp3 r0.x, v1.xyzx, cb1[4].xyzx
          dp3 r0.y, v1.xyzx, cb1[5].xyzx
          dp3 r0.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r0.xyzx, r0.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o1.xyz, r0.wwww, r0.xyzx
          mul r0.xyz, v2.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v2.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v2.zzzz, r0.xyzx
          dp3 r0.w, r0.xyzx, r0.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o2.xyz, r0.wwww, r0.xyzx
          mov o2.w, v2.w
          mov o3.xyzw, v3.xyzw
          mov o4.xyzw, v5.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float       
          // INTERP                   3   xyzw        4     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_input_ps linear v1.xyz
          dcl_output o0.xyzw
          dcl_temps 1
          dp3 r0.x, v1.xyzx, v1.xyzx
          rsq r0.x, r0.x
          mul o0.xyz, r0.xxxx, v1.xyzx
          mov o0.w, l(0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 3, name: ShadowCaster
    {
      Name "ShadowCaster"
      Tags
      { 
        "LIGHTMODE" = "SHADOWCASTER"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      ColorMask 0
      GpuProgramID 166645
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2032
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Vector value_type=float4 name=_ShadowBias offset=1984 arraySize=0
          //    cbIndex=0 type=Vector value_type=float3 name=_LightDirection offset=2000 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[126], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mad r0.xyz, cb0[125].xyzx, cb0[124].xxxx, r0.xyzx
          dp3 r1.x, v1.xyzx, cb1[4].xyzx
          dp3 r1.y, v1.xyzx, cb1[5].xyzx
          dp3 r1.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r1.xyzx, r1.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul r1.xyz, r0.wwww, r1.xyzx
          dp3_sat r0.w, cb0[125].xyzx, r1.xyzx
          add r0.w, -r0.w, l(1.000000)
          mul r0.w, r0.w, cb0[124].y
          mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
          mov o1.xyz, r1.xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add r0.xyzw, r0.xyzw, cb0[76].xyzw
          min o0.z, r0.z, l(1.000000)
          mov o0.xyw, r0.xyxw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float       
          // INTERP                   1   xyzw        2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_output o0.xyzw
          mov o0.xyzw, l(0,0,0,0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 4, name: DepthNormals
    {
      Name "DepthNormals"
      Tags
      { 
        "LIGHTMODE" = "DepthNormalsOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      GpuProgramID 332422
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          vs_5_0
          dcl_globalFlags refactoringAllowed
          dcl_constantbuffer CB0[77], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r0.xyzw, cb0[76].xyzw
          dp3 r0.x, v1.xyzx, cb1[4].xyzx
          dp3 r0.y, v1.xyzx, cb1[5].xyzx
          dp3 r0.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r0.xyzx, r0.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o1.xyz, r0.wwww, r0.xyzx
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_5_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_5_0
          dcl_globalFlags refactoringAllowed
          dcl_input_ps linear v1.xyz
          dcl_output o0.xyzw
          dcl_temps 1
          dp3 r0.x, v1.xyzx, v1.xyzx
          rsq r0.x, r0.x
          mul o0.xyz, r0.xxxx, v1.xyzx
          mov o0.w, l(0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  SubShader
  {
    Tags
    { 
      "QUEUE" = "Transparent"
      "RenderPipeline" = "UniversalPipeline"
      "RenderType" = "Transparent"
      "ShaderGraphShader" = "true"
      "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
      "UniversalMaterialType" = "Unlit"
    }
    Pass // ind: 1, name: Universal Forward
    {
      Name "Universal Forward"
      Tags
      { 
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      ZWrite Off
      Blend SrcAlpha One, One One
      GpuProgramID 453912
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixV offset=976 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Vector value_type=float3 name=_WorldSpaceCameraPos offset=256 arraySize=0
          //    cbIndex=0 type=Vector value_type=float4 name=unity_OrthoParams offset=336 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyz         2     NONE   float   xyz 
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          // INTERP                   3   xyzw        4     NONE   float   xyzw
          // INTERP                   4   xyz         5     NONE   float   xyz 
          //
          vs_4_0
          dcl_constantbuffer CB0[77], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyz
          dcl_output o3.xyzw
          dcl_output o4.xyzw
          dcl_output o5.xyz
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r1.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r1.xyzw, cb0[76].xyzw
          mov o1.xyz, r0.xyzx
          add r0.xyz, -r0.xyzx, cb0[16].xyzx
          dp3 r1.x, v1.xyzx, cb1[4].xyzx
          dp3 r1.y, v1.xyzx, cb1[5].xyzx
          dp3 r1.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r1.xyzx, r1.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o2.xyz, r0.wwww, r1.xyzx
          mov o3.xyzw, v3.xyzw
          mov o4.xyzw, v4.xyzw
          eq r0.w, cb0[21].w, l(0.000000)
          movc o5.x, r0.w, r0.x, cb0[61].z
          movc o5.y, r0.w, r0.y, cb0[62].z
          movc o5.z, r0.w, r0.z, cb0[63].z
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Vector value_type=float2 name=_GlobalMipBias offset=304 arraySize=0
          //
          // Uniform=1 type=Texture value_type=Texture2D name=_MainTex index=0 samplerIndex=0 multiSampled=0
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float       
          // INTERP                   1   xyz         2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float   xy  
          // INTERP                   3   xyzw        4     NONE   float   xyzw
          // INTERP                   4   xyz         5     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_constantbuffer CB0[20], immediateIndexed
          dcl_sampler s0, mode_default
          dcl_resource_texture2d (float,float,float,float) t0
          dcl_input_ps linear v3.xy
          dcl_input_ps linear v4.xyzw
          dcl_output o0.xyzw
          dcl_temps 4
          sample_b r0.xyzw, v3.xyxx, t0.xyzw, s0, cb0[19].x
          add r1.xyz, -r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
          mul r1.xyz, r1.xyzx, r1.xyzx
          mad r1.xyz, -r1.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(1.000000, 1.000000, 1.000000, 0.000000)
          ge r2.xyz, l(0.500000, 0.500000, 0.500000, 0.000000), r0.xyzx
          movc r3.xyz, r2.xyzx, l(0,0,0,0), l(1.000000,1.000000,1.000000,0)
          and r2.xyz, r2.xyzx, l(0x3f800000, 0x3f800000, 0x3f800000, 0)
          mul r1.xyz, r1.xyzx, r3.xyzx
          mul r0.xyz, r0.xyzx, r0.xyzx
          add r0.xyz, r0.xyzx, r0.xyzx
          mad r0.xyz, r0.xyzx, r2.xyzx, r1.xyzx
          mul o0.xyzw, r0.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 2, name: DepthNormalsOnly
    {
      Name "DepthNormalsOnly"
      Tags
      { 
        "LIGHTMODE" = "DepthNormalsOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      GpuProgramID 477368
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float   xyzw
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // TEXCOORD                 1   xyzw        4     NONE   float       
          // COLOR                    0   xyzw        5     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          // INTERP                   3   xyzw        4     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[77], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v2.xyzw
          dcl_input v3.xyzw
          dcl_input v5.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_output o4.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r0.xyzw, cb0[76].xyzw
          dp3 r0.x, v1.xyzx, cb1[4].xyzx
          dp3 r0.y, v1.xyzx, cb1[5].xyzx
          dp3 r0.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r0.xyzx, r0.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o1.xyz, r0.wwww, r0.xyzx
          mul r0.xyz, v2.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v2.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v2.zzzz, r0.xyzx
          dp3 r0.w, r0.xyzx, r0.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o2.xyz, r0.wwww, r0.xyzx
          mov o2.w, v2.w
          mov o3.xyzw, v3.xyzw
          mov o4.xyzw, v5.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float       
          // INTERP                   3   xyzw        4     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_input_ps linear v1.xyz
          dcl_output o0.xyzw
          dcl_temps 1
          dp3 r0.x, v1.xyzx, v1.xyzx
          rsq r0.x, r0.x
          mul o0.xyz, r0.xxxx, v1.xyzx
          mov o0.w, l(0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 3, name: ShadowCaster
    {
      Name "ShadowCaster"
      Tags
      { 
        "LIGHTMODE" = "SHADOWCASTER"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      ColorMask 0
      GpuProgramID 555844
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2032
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=0 type=Vector value_type=float4 name=_ShadowBias offset=1984 arraySize=0
          //    cbIndex=0 type=Vector value_type=float3 name=_LightDirection offset=2000 arraySize=0
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[126], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mad r0.xyz, cb0[125].xyzx, cb0[124].xxxx, r0.xyzx
          dp3 r1.x, v1.xyzx, cb1[4].xyzx
          dp3 r1.y, v1.xyzx, cb1[5].xyzx
          dp3 r1.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r1.xyzx, r1.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul r1.xyz, r0.wwww, r1.xyzx
          dp3_sat r0.w, cb0[125].xyzx, r1.xyzx
          add r0.w, -r0.w, l(1.000000)
          mul r0.w, r0.w, cb0[124].y
          mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
          mov o1.xyz, r1.xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add r0.xyzw, r0.xyzw, cb0[76].xyzw
          min o0.z, r0.z, l(1.000000)
          mov o0.xyw, r0.xyxw
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float       
          // INTERP                   1   xyzw        2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_output o0.xyzw
          mov o0.xyzw, l(0,0,0,0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
    Pass // ind: 4, name: DepthNormals
    {
      Name "DepthNormals"
      Tags
      { 
        "LIGHTMODE" = "DepthNormalsOnly"
        "QUEUE" = "Transparent"
        "RenderPipeline" = "UniversalPipeline"
        "RenderType" = "Transparent"
        "ShaderGraphShader" = "true"
        "ShaderGraphTargetId" = "UniversalUnlitSubTarget"
        "UniversalMaterialType" = "Unlit"
      }
      GpuProgramID 752304
      // m_ProgramMask = 6
      !!! *******************************************************************************************
      !!! Allow restore shader as UnityLab format - only available for DevX GameRecovery license type
      !!! *******************************************************************************************
      Program "vp"
      {
        SubProgram "d3d11"
        {
          
          "!!vs_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          // ConstantBuffer[0] name=$Globals type=ConstantBuffer size=2000
          //    cbIndex=0 type=Matrix value_type=float4x4 name=unity_MatrixVP offset=1168 arraySize=0 matrix_dir_type=row_major
          //
          // ConstantBuffer[1] name=UnityPerDraw type=ConstantBuffer size=656
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_ObjectToWorld offset=0 arraySize=0 matrix_dir_type=row_major
          //    cbIndex=1 type=Matrix value_type=float4x4 name=unity_WorldToObject offset=64 arraySize=0 matrix_dir_type=row_major
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // POSITION                 0   xyz         0     NONE   float   xyz 
          // NORMAL                   0   xyz         1     NONE   float   xyz 
          // TANGENT                  0   xyzw        2     NONE   float       
          // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
          // COLOR                    0   xyzw        4     NONE   float   xyzw
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float   xyzw
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float   xyzw
          // INTERP                   2   xyzw        3     NONE   float   xyzw
          //
          vs_4_0
          dcl_constantbuffer CB0[77], immediateIndexed
          dcl_constantbuffer CB1[7], immediateIndexed
          dcl_input v0.xyz
          dcl_input v1.xyz
          dcl_input v3.xyzw
          dcl_input v4.xyzw
          dcl_output_siv o0.xyzw, position
          dcl_output o1.xyz
          dcl_output o2.xyzw
          dcl_output o3.xyzw
          dcl_temps 2
          mul r0.xyz, v0.yyyy, cb1[1].xyzx
          mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
          mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
          add r0.xyz, r0.xyzx, cb1[3].xyzx
          mul r1.xyzw, r0.yyyy, cb0[74].xyzw
          mad r1.xyzw, cb0[73].xyzw, r0.xxxx, r1.xyzw
          mad r0.xyzw, cb0[75].xyzw, r0.zzzz, r1.xyzw
          add o0.xyzw, r0.xyzw, cb0[76].xyzw
          dp3 r0.x, v1.xyzx, cb1[4].xyzx
          dp3 r0.y, v1.xyzx, cb1[5].xyzx
          dp3 r0.z, v1.xyzx, cb1[6].xyzx
          dp3 r0.w, r0.xyzx, r0.xyzx
          max r0.w, r0.w, l(0.000000)
          rsq r0.w, r0.w
          mul o1.xyz, r0.wwww, r0.xyzx
          mov o2.xyzw, v3.xyzw
          mov o3.xyzw, v4.xyzw
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "fp"
      {
        SubProgram "d3d11"
        {
          
          "!!ps_4_0
          
          // Options.AllowRestoreShaderAsUnityLab=False
          // WARNING: Convert DirectX Shader to UnityLab Shader support only for GameRecovery license type!
          //
          //
          // Shader params:
          //
          //
          // ConstantBuffers:
          //
          //
          //
          // Generated by Microsoft (R) D3D Shader Disassembler
          //
          //
          // Input signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_POSITION              0   xyzw        0      POS   float       
          // INTERP                   0   xyz         1     NONE   float   xyz 
          // INTERP                   1   xyzw        2     NONE   float       
          // INTERP                   2   xyzw        3     NONE   float       
          //
          //
          // Output signature:
          //
          // Name                 Index   Mask Register SysValue  Format   Used
          // -------------------- ----- ------ -------- -------- ------- ------
          // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
          //
          ps_4_0
          dcl_input_ps linear v1.xyz
          dcl_output o0.xyzw
          dcl_temps 1
          dp3 r0.x, v1.xyzx, v1.xyzx
          rsq r0.x, r0.x
          mul o0.xyz, r0.xxxx, v1.xyzx
          mov o0.w, l(0)
          ret 
          // Approximately 0 instruction slots used
          
          
          
          "
        }
      }
      Program "gp"
      {
      }
      Program "hp"
      {
      }
      Program "dp"
      {
      }
      Program "surface"
      {
      }
      Program "rtp"
      {
      }
      
    } // end phase
  }
  FallBack "Hidden/Shader Graph/FallbackError"
}
