using UnityEngine;

namespace ProjectArk.Level
{
    /// <summary>
    /// Lightweight snapshot of a room's map-relevant data.
    /// Generated by MinimapManager from Room + RoomSO at runtime.
    /// Used by MapPanel and MinimapHUD to render room nodes.
    /// </summary>
    public struct MapRoomData
    {
        /// <summary> Unique room identifier. </summary>
        public string RoomID;

        /// <summary> Display name for tooltips / labels. </summary>
        public string DisplayName;

        /// <summary> World-space center of the room (from BoxCollider2D bounds). </summary>
        public Vector2 WorldCenter;

        /// <summary> World-space size of the room (from BoxCollider2D bounds). </summary>
        public Vector2 WorldSize;

        /// <summary> Floor level (0 = surface, -1 = underground). </summary>
        public int FloorLevel;

        /// <summary> Room type — determines node color on the map. </summary>
        public RoomType Type;

        /// <summary> Optional map icon override (from RoomSO). </summary>
        public Sprite MapIcon;

        /// <summary> Whether the player has visited this room at least once. </summary>
        public bool IsVisited;

        /// <summary> Whether this is the room the player is currently in. </summary>
        public bool IsCurrent;
    }
}
